[1단계 - 자판기] 시지프(김의진) 미션 제출합니다.
woowacourse/javascript-vendingmachine pull request #10
Opened 2022-03-26 04:35 UTC by euijinkk

안녕하세요 월터님! 시지프 라고합니다.
자판기 미션 잘 부탁드립니다!!
자판기 미션에 대해서 많은 이야기 나누어보면 좋겠습니다.
편하게 리뷰해주세요!😄

## [데모페이지](https://euijinkk.github.io/javascript-vendingmachine/)

<br>

## 프로젝트 구조 도식화

<img width="60%" src="https://user-images.githubusercontent.com/24906022/160223273-a3959391-a03e-4496-8847-cd63a20440bd.png" />

기본적으로 UI와 Domain을 분리하려고 노력했습니다. 그러는 과정에서 UI와 Domain 간의 의존, UI간의 의존이 발생했습니다. 현 프로젝트 상 UI와 Domain의 의존으로 큰 불편함은 느끼지 않아 중재 파일을 만들지 않았습니다. 그리고 UI간의 의존으로 구조가 복잡해질 것이라고 생각하여, UI를 연결해주는 `ViewPainter` 클래스를 만들었습니다. 한 UI 클래스에서 이벤트가 발생했을 때, 다른 UI 클래스의 render 를 대신 실행해주는 역할을 합니다. 그럼으로써 UI 간의 의존을 끊어내고자 했습니다.

그리고 UI를 페이지 별로 구분하지 않고, 페이지 내에서도 잘게 구성하려고 노력했습니다. 한 UI 클래스에 이벤트가 여러개 들어가면 파일이 커지고, 읽기가 어려워서 분리했습니다.
예를 들어 `ProductManagementUI` 안에는 `ProductAdditionUI`와 `ProductInventoryUI`가 있습니다. `ProductManagementUI` 안에서 전체 template을 그려주고, `ProductAdditionUI`와 `ProductInventoryUI`에서 이벤트를 부착해주는 구조로 했습니다. 지금은 문제가 없어 보이지만, 파일이 깊어지고, 확장될 것을 생각하면 세부 UI 클래스에서 template을 따로 그려줘야 할 것같습니다.

<br>

## 개발 주안점

### 패턴에 얽매이지 않고, 우리의 생각과 의도가 담긴 코드를 짜려고 노력했습니다.

### TypeScript
먼저 TypeScript로 Domain을 모델링 하였습니다. class를 구상하여 interface를 짜고, 이를 implements 하여 domain을 짜나갔습니다. 그 과정에서 미리 어떤 타입으로 어떤 매개변수가 들어오고, 어떻게 return 할지 메소드를 구상하고, 어떤 멤버변수가 존재해야할지 구상하여 높은 완성도로 domain을 짤 수 있었습니다. 

타입 선언 중복을 최소화 하기 위하여, keyof, mapped type을 적극 활용해보았습니다.

미션 완수 후 시간이 조금 남아 UI도 TypeScript로 변환해보았습니다. as, any 없이 사용하려고 했는데, 몇개는 narrowing에 실패하거나, narrowing하는 과정이 복잡하여 as 로 선언해주었습니다.

### TDD
TypeScript로 모델링 하면서 TDD를 수행해보았습니다. 모델링을 하고 나면, 어떤 메소드가 어떤 형태로 정의되는지 알고 있기 때문에 TDD 하기 매우 수월했습니다. Domain을 모델링하고 TDD하는 경험이 좋았습니다.

test 시에 테스트 별로 독립성을 유지하기 위해서, magic number를 사용하지 않기 위해서 노력했습니다.

### scss
scss의 nesting 기능과 & 기능이 매력적이어서 scss를 사용했습니다. 사용 결과 html 구조와 비슷한 스타일링을 할 수 있어서 굉장히 편했습니다. BEM과 함께 적용하니 더욱 좋았습니다.

### 사용성
몇가지 측면에서 사용성을 고려해보았습니다.
- 탭 이동 시 input에 focus
- 상품 추가 시, invalid한 input이 있다면 alert를 띄우고, invalid input으로 focus 이동
- 상품 정보 수정을 누르면 input에 focus
- 상품 정보 수정 후 Enter 누르면 수정되도록

## 질문
- typescript에서 private을 지원하고, javascript에서 #을 지원하고 있습니다. 이번에 모두 private으로 선언하고자 했으나, private member variable을 선언하면, 동일한 이름을 getter를 사용할 수 없었습니다. 그래서, getter가 필요한 변수에 대해서만 #로 처리해주었습니다. 일관성이 조금 부족할 수도 있다는 생각이 드는데, 멤버변수는 #으로, method는 private으로 처리해주는 것은 어떻게 생각하시는지 궁금합니다!
- 커밋 단위에 대해 고민이 생겼는데, 월터님은 어떻게 하시는지 궁금합니다. 
    1. 먼저 "기능단위로 커밋하라!"를 생각하며 하고 있는데, "기능"을 정의할 때 UI와 Domain을 합친 것을 기능이라 불러야할지, UI와 Domain을 따로 기능이라고 불러야할 지 모호했습니다. 저는 커밋은 history를 관리하고, rollback하기 위해서 해야한다고 생각을 해서, 잘게 나눠서 따로 커밋해주는 것이 좋다고 판단했습니다.
    2. 두번째로 test의 커밋을 어떤 단위로 해야할지 의문이었습니다. 상품관리 method 테스트, 상품관리 validation 테스트 등 크게크게 나누어서 커밋을 했는데, it 단위로 하나하나 해야할까? 하는 고민도 들었습니다. 월터님은 평소에 어떻게 하시는지 궁금합니다!
- 이번 미션은 그때 그때 개발하다가, 확장성에 대응하는 방식으로 개발했습니다. 이전 미션에서는 처음부터 MVC 패턴이나, 컴포넌트 구조 등을 사용하여 이미 확장성이 있는 패턴들을 사용해서 제가 그것에 대응해야할 일은 별로 없었습니다. 그런데 이번에는 패턴 없이 개발하면서 확장성이 필요할 때마다 페어와 고민하여 대응해주었습니다. 그래서 이 구조가 다소 확장성이 부족해보일 수 있다고 생각하고, 개선되어야할 부분이 있다고 생각합니다. 월터님은 혹시 어떤 부분에서 확장성이 부족하다고 느끼시는지 궁금합니다!

2022-03-27 13:56 UTC, inwalter99 commented
> 커밋 단위에 대해 고민이 생겼는데, 월터님은 어떻게 하시는지 궁금합니다

저는 일단 커밋은 "가능한 작게" 하는 것을 선호합니다. 함수를 작성할 때 하나의 일만 하도록 하는 것처럼 커밋의 내용도 하나의 주제만 갖고 있어야 한다고 생각하는데요, 그 이유는 히스토리를 파악하는 데 용이하고, 때에 따라 커밋만 가져오거나 되돌릴 때도 사이드 이펙트가 적게 할 수도 있기 때문입니다. 시지프님이 생각하신 1번과 동일한 생각입니다. 저는 커밋을 작성할 때 "이 커밋의 제목이 내가 작성한 코드를 설명할 수 있는가?"를 되묻곤 합니다. 나중에 히스토리 파악할 때 커밋의 제목을 가장 먼저 보게 되거든요... 생뚱맞은 제목이 보이는 순간 혼란의 시작ㅋ.. 테스트도 위의 말한 것과 비슷하게 작성하는데 비교적 히스토리 파악 등 할 이유가 적어서 좀 신경을 덜 쓰는 것 같긴합니다 ;ㅁ;

2022-03-27 13:56 UTC, inwalter99 commented
> 월터님은 혹시 어떤 부분에서 확장성이 부족하다고 느끼시는지 궁금합니다!

"보통 확장성이 높다."라는 말은 "변화에 유연하다."라는 말과 동일하다고 생각합니다. 코드를 예를 들면, 어떠한 컴포넌트가 추가/삭제 될 때 다른 코드에 영향이 적으면 적을 수록 확장성이 높다고 하는 것 같고 마찬가지로 외부 요소가 변경되었을 때도 내부 코드에 영향을 최소화할 수 있는 상황이 확장성이 높은 상황인 것 같습니다. 

UI/Domain/ViewPainter 구조에서 확장성을 고려해보자면, 지금은 데이터를 바꿔준 후 렌더링을 명시적으로 하고 있는데, 나중에 상태를 바꿨을 때 자동으로 렌더링으로 일어나게끔 한다고 가정해본다고 구조를 생각해봤을 땐 수정이 꽤 덜할 것 같습니다 ;) 물론 Domain/ViewPainter 는 날라가겠지만 UI 는 거의 그대로 사용할 수 있을 것 같다는 점에서 저는 확장성이 나쁘지 않다고 생각합니다.

2022-03-27 14:16 UTC, inwalter99 requested changes
> 주말이라 늦게 리뷰드려 죄송합니다 ;ㅁ;

안녕하세요 시지프님 :) 반갑습니다.
저도 많은 이야기 나눌 수 있길 기대해보겠습니다!

전반적으로 코드가 잘 작성되어있는 것 같습니다. 
덕분에 코드에 대한 코멘트는 적게 드린 것 같아요ㅎ 드린 코멘트 확인부탁드리겠습니다

2022-03-27 14:16 UTC, yongholeeme commented on src/ts/__test__/validator.test.ts
> +    };
디폴트 값을 만들어 테스트의 의도를 더 잘 드러냈으면 좋겠습니다.
```js
const newProduct = {
  ...defaultProduct,
  name: ''
}
```

2022-03-27 14:16 UTC, yongholeeme commented on src/ts/__test__/validator.test.ts
> +    );
각 함수들을 테스트하는 게 아니라 유효성을 검증하는 함수들을 묶어 하나의 validateProductInfo 를 ~통합테스트~유닛테스트를 하고 있는데요! 
사실 isQuantityRanged 를 보고 함수의 이름만으로는 행동과 목적이 예상이 안가서; 테스트를 찾는데 이 테스트 케이스가 isQuantityRanged 를 테스트를 하고 있다는 걸 한참에서야 찾았습니다 ;ㅁ; 케이스별 내용을 다 읽어야해서...

~그리고 지금 이 테스트 케이스가 온전히 isQuantityRanged 에 의해서만 성공/실패하고 있다고 단언할 수 있을까요 ? 👀~
지금은 각 유효성 검증 함수에 대해 MESSAGE 를 특정 지었기 때문에 범인을 쉽게 찾을 수 있을 것 같은데요! 보통 ~통합테스트~유닛테스트같은 경우는 범인(?)을 쉽게 찾기 어렵고 유지/보수 측면에서 계속해서 사이드이펙트도 고려해야하기 때문에 독립적인 테스트인 유닛테스트를 진행을 하는 것 같습니다 :0 
지금같은 경우는 메시지를 통해 특정지을 순 있어서 ..개선할 필요는 없을 것 같네요!

2022-03-27 14:16 UTC, yongholeeme commented on src/ts/__test__/coin.test.ts
> +    const coinDomain = new CoinManagementDomain();
아직 코드와 구조를 다 읽지 못해서 느낌을 제대로 이해는 못했는데
시지프님이 CoinManagementDomain 를 coinDomain라는 변수에 할당하는 것 보면 ... CoinManagementDomain 의 이름에서 Management 는 빼도 될까 라는 생각이 드네요...

2022-03-27 14:16 UTC, yongholeeme commented on src/ts/__test__/coin.test.ts
> +      (prev, current) => prev + Number(current) * coins[current],
prev 보단 acc 를 좀 더 많이 쓰는 것 같아요... prev는 바로 이전 값을 연상시키니까요..!

2022-03-27 14:16 UTC, yongholeeme commented on src/ts/ui/ProductManagementUI/ProductAdditionUI.ts
> +    };
$$ 는 무슨 의미를 담은 네이밍 컨벤션일까요?

2022-03-27 14:16 UTC, yongholeeme commented on src/ts/constants/index.ts
> +  }원 이상 ${PRICE_RULE.MAX.toLocaleString()}원 이하여야 하며, ${
toLocaleString 을 유틸화해서 금액을 나타내는 모든 부분에 적용해보면 어떨까요?

2022-03-27 14:16 UTC, yongholeeme commented on src/ts/ui/CoinManagementUI/CoinChargeUI.ts
> +    const cash = cashInput.valueAsNumber;
오오. valueAsNumber 로 값을 가져 올 수 있는 건 저도 처음 알게 됐어요!

2022-03-27 14:16 UTC, yongholeeme commented on src/ts/ui/ProductManagementUI/ProductAdditionUI.ts
> +  private focusOnInvalidInput(target: ProductInfoUnionType, $$inputs: Inputs) {
👍

2022-03-27 14:16 UTC, inwalter99 commented on src/ts/domain/CoinManagement.ts
> +export default class CoinManagementDomain implements CoinManagement {
지금 구조에서 CoinManagement 가 가진 장점?역할이 뭘까요?!

2022-03-27 14:18 UTC, inwalter99 commented
앗 그리고 UI 보다는 Component 라는 이름은 어떨까요? 프론트엔드에선 UI 모듈을 보통 컴포넌트라고 지칭을 해서 UI 보단 Component 가 조금 더 익숙한 네이밍 같아요 ;)

2022-03-27 14:20 UTC, inwalter99 commented
아.. 계속 까먹네요ㅋ 지금 라우팅 코드 쪽에 문제가 있는 것 같아요~ 그 부분도 확인해보면 좋을 것 같습니다 ;) 

https://user-images.githubusercontent.com/28642472/160285925-58a85f81-d920-4bd3-8970-da8081fd60c6.mov

2022-03-28 16:00 UTC, euijinkk commented on src/ts/domain/CoinManagement.ts
> +    coinType.forEach(type => (this.#coins[type] = 0));
```javascript
this.#coins = coinType.reduce((object, type) => {
      object[type] = 0;
      return object;
    }, {});
```

초기화 + forEach를 reduce 고차함수로 바꿀 수 있을 것같습니다. 그런데, reduce는 바로 읽히지가 않아서 reduce를 써야할까 고민했습니다.
초기화 + 반복문을 수행한다는 점에서 코드 효율성이 동일하다고 생각했기 때문에, 가독성이 좋은 forEach로 구현했습니다.

그렇지만 reduce에서 객체를 생성하는 방식이 저희에게 익숙하지 않아서 그런 것일까 하는 의문이 들었습니다. 
저 형태의 reduce가 자주 사용되는지, 월터님은 잘 읽히는지 궁금하여 질문드립니다!

2022-03-28 16:00 UTC, euijinkk commented on src/ts/domain/Product.ts
> +export default class ProductImpl implements Product {
Interface 네이밍이 너무 어렵네요. 예전에 I-prefix를 사용했는데, 이는 헝가리안 표기법이고, interface를 표기하는 upper camel case와 상응하지 않아 지양해야한다는 글을 보았습니다.

I-prefix를 지양하려고 했더니 네이밍이 너무 어려웠습니다. 자바에서 class 명을 Impl-suffix로 표기하는 방식을 사용한다는 글을 보아서 적용해보았습니다.

월터님은 interface 네이밍 어떻게 하시는지 궁금합니다!

2022-03-28 16:00 UTC, euijinkk commented on src/ts/ui/ProductManagementUI/ProductAdditionUI.ts
> +    };
각 input을 하나하나 narrowing 해주는게 너무 복잡하고 과하다고 생각하여 as를 사용했습니다..

2022-03-28 16:00 UTC, euijinkk commented on src/ts/__test__/coin.test.ts
> +      (prev, current) => prev + Number(current) * coins[current],
앗, 좋습니다!

2022-03-28 16:00 UTC, euijinkk commented on src/ts/__test__/coin.test.ts
> +    const coinDomain = new CoinManagementDomain();
너무 길어서, 함부로 축약해서 사용했다는 느낌이 드네요.
Management와 Domain이 중복된 느낌도 있어서 둘중 하나를 빼는 것도 좋은 것 같습니다. 
CoinDomain으로 가겠습니다!

2022-03-28 16:00 UTC, euijinkk commented on src/ts/__test__/validator.test.ts
> +    };
오오!! 훨씬 의미가 명확해지는 것 같습니다. 

[144a246](https://github.com/woowacourse/javascript-vendingmachine/pull/10/commits/144a246835bd79b3190b47c1475347024059f64f) 수정했습니다!

2022-03-28 16:00 UTC, euijinkk commented on src/ts/constants/index.ts
> +  }원 이상 ${PRICE_RULE.MAX.toLocaleString()}원 이하여야 하며, ${
지금은 백단위 이하이지만, 천 단위 이상이 될 것을 고려해 적용해두는 것도 좋겠네요.
그런데, 그냥 toLocaleString 메소드를 적용하면 되지 않을까 싶은데, 혹시 유틸화를 제안하신건 가독성을 위해서 일까요?

일단은 toLocaleString을 [적용했습니다.](https://github.com/woowacourse/javascript-vendingmachine/pull/10)

2022-03-28 16:00 UTC, euijinkk commented on src/ts/domain/CoinManagement.ts
> +export default class CoinManagementDomain implements CoinManagement {
아하, 이번에 modeling을 위해서 interface를 만들고, implements 하는 방식으로 코드를 짰습니다. 
1. 이미 구현을 해서 쓸모가 없어지고
2. 다른 Class에 재사용할 일이 없다면

지우는 것이 나을 것 같습니다. 
[d887970](https://github.com/woowacourse/javascript-vendingmachine/pull/10/commits/d8879703f6acf35c3f21f4c83d7d28f7fafb3301)

2022-03-28 16:00 UTC, euijinkk commented on src/ts/ui/ProductManagementUI/ProductAdditionUI.ts
> +    };
$$은 2개 이상의 DOM을 가지고 있는 배열/유사배열/객체를 가리키는 컨벤션으로 사용해보았습니다!

2022-03-28 16:00 UTC, euijinkk commented on src/ts/__test__/validator.test.ts
> +    );
아하 저도 이부분이 매우 고민이었습니다. 
unit test 시에, 메소드 테스트해야할 지, 실제 사용하는 함수로 테스트해야할지 고민이었습니다.

좀 더 명확한 의미를 가지기 위해서 각각의 validate 메소드들(isQuantityRanged, isOverMaxLength 등)을 검증할 수도 있다고 생각했습니다.

하지만 저는 validateProductInfo를 적용하여 validate 하고 있으니, 이 함수를 사용하여 검증하고자 하였습니다.

unit 테스트는 각 메소드 단위로 테스트 하는 것이 적절한지 묻고 싶습니다!

2022-03-28 16:12 UTC, euijinkk commented
1. UI보다 Component가 더 잘 어울리는 것 같아 변경했습니다.
2. 라우팅 문제 해결했습니다 (/ 가 하나 빠져있었네요..)
3. 커밋에 대한 코멘트, 확장성에 대한 코멘트 감사합니다. 참고하여 2단계 진행해보겠습니다.

code에 남긴 질문 한번 봐주시면 감사하겠습니다! ( [reduce vs forEach](https://github.com/woowacourse/javascript-vendingmachine/pull/10#discussion_r835713602), [interface 이름 짓기](https://github.com/woowacourse/javascript-vendingmachine/pull/10#discussion_r835714409), [as 사용](https://github.com/woowacourse/javascript-vendingmachine/pull/10#discussion_r835715623))

2022-03-29 11:22 UTC, inwalter99 commented on src/ts/__test__/validator.test.ts
> +    );
> 일부 잘못된 표현이 있어서 정정했습니다! 통합 -> 유닛

말씀주신 고민은 각 메서드를 테스트해야할지, 실제 사용하는 함수를 테스트해야할 지보단 유닛 테스트의 대상의 크기를 어느정도로 잡으면 좋을까에 대한 고민에 더 가까운 것 같습니다. 당연하게도 정답은 없지만, 제 생각을 말씀드려보자면 이 상황에선 각 메서드 단위로 테스트할 것 같습니다. 테스트코드도 결국엔 유지보수의 대상인데요. 만약에 이 테스트 케이스가 깨졌을 때, 시지프님이 아닌 다른 사람이 이 테스트코드를 봤을 때 바로 `isQuantityRanged` 로 특정지어 문제를 해결할 수 있을까요? 테스트코드는 대상 함수의 명세가 되기도 하는데, 이 부분에서 validateProductInfo 라는 함수 내에서 동작하게 되어 isQuantityRanged를 한 번에 캐치하기 어렵다고 느껴졌습니다.

다른 관점에서 validateProductInfo 의 역할은 `각 메서들을 모아서 한 번에 유효성 검사를 한다.`고 생각하는데 사실 역할은 모아주는 것 외에 없다고 생각했습니다. 만약 validateProductInfo 에 대한 테스트가 깨졌을 경우 그 안에 있는 것들을 한 번 더 범인을 찾기 위한 단계가 늘어난다고 생각해서 저는 최소한의 단위로 진행을 하게 될 것 같습니다..!
이 부분에서 시지프님은 MESSAGE 로 범인을 거의 특정하게 될 수 있어서 지금도 괜찮다고 말씀드려봤습니다!

2022-03-29 11:26 UTC, inwalter99 commented on src/ts/ui/ProductManagementUI/ProductAdditionUI.ts
> +    };
`Elements` 만으로도 충분히 예측이 가능하다고 생각하고 복수형 `s` 으로 배열의 의미를 담아주고 계셔서, 중복되는 네이밍이 아닐까 싶은데 어떻게 생각하시나요..! 
물론 $ 라는 prefix 를 element 의미로 쓰는 걸 종종 보긴했습니다! 

> 사담으로(?) 저희팀에선 observable 한 변수에 $를 붙여주고 있어요ㅋㅋ

2022-03-29 11:36 UTC, inwalter99 commented on src/ts/constants/index.ts
> +  }원 이상 ${PRICE_RULE.MAX.toLocaleString()}원 이하여야 하며, ${
단순 숫자를 포맷팅한다기보단 금액을 포맷팅한다고 생각했는데요. 그래서 유틸화 해놓는다면 소수점 대응이나 나중에 formatting 이 달라졌을 때 + 단위까지 쉽게 대응할 수 있다고 생각했는데요, 
저야말로 좀 더 과하게 의견을 드린 거 같네요ㅜㅜ; 이견없습니다. 핀테크쪽에서 일해서 금액 포맷팅하는데 많이 혼쭐이 나서 그렇습니다ㅜㅜㅋ

2022-03-29 11:40 UTC, inwalter99 commented on src/ts/domain/CoinManagement.ts
> +    coinType.forEach(type => (this.#coins[type] = 0));
reduce 를 이용해서 객체를 생성하거나 등 하는 로직은 굉장히 왕왕 자주 사용되는데요 말씀주신 것처럼 저도 가독성이 forEach가 높다는 거에 공감합니다. 저는 보통 reduce 로 먼저 작성한 후 가독성이 떨어진다 싶으면, 가독성이 높은 방향으로 리팩터링하는 편입니다. 성능차이는 크게 없다면 이걸 나중에 유지보수한다는 측면에선 가독성이 높은게 좋아야 한다는 주의입니다 ㅎ;;

Is reduce() bad~~~? 에 대해서 유튜브가 하나 있는데 심심하실 때 한 번 보시면 좋을 것 같아요 ㅎㅎ
https://www.youtube.com/watch?v=qaGjS7-qWzg

2022-03-29 11:57 UTC, inwalter99 commented on src/ts/domain/Product.ts
> +export default class ProductImpl implements Product {
일단 지금 상황에서 인터페이스가 필요했나?라는 질문을 다시금 던져볼 것 같구요. 저는 그냥 `export default class Product` { 로 작성할 것 같네요...
일단 네이밍이 겹칠 일이 크게 없었던 것 같은데요, 예를 들어 `PopupError` 라는 인터페이스를 정의했으면 `class ConnectPopupError implements PopupError` 이런식으로 인터페이스를 활용하기 때문에 I prefix 없이도 잘 활용했던 것 같습니다. 

별도 인터페이스에 대해 네이밍 컨벤션을 따로 지키고 있진 않습니다! I 를 쓰자! 라는 컨벤션을 만들어버리면 그만일 수도 있겠지만, 말씀해주신 헝가리안 표기법을 인터페이스에만 쓰는 것 자체가 일괄성을 깨뜨리는 게 아닐까 생각도 합니다..

2022-03-29 11:58 UTC, inwalter99 commented on src/ts/ui/ProductManagementUI/ProductAdditionUI.ts
> +    };
하나하나 narrowing 해준다는 게 무슨 말씀이실까요 @.@?

2022-03-29 12:00 UTC, inwalter99 requested changes
커밋을 잘 나눠주셔서 손쉽게 추가 작업 확인했습니다!
질문 주신 것들에 답변달았습니다! 확인해주세요~!

좋은 질문들 많이 해주셔서 감사합니다ㅎㅎ

2022-03-29 14:22 UTC, euijinkk commented on src/ts/domain/CoinManagement.ts
> +    coinType.forEach(type => (this.#coins[type] = 0));
우와!!

자주 사용된다군요.
유튜브 영상 참고하겠습니다! 
의견 감사합니다~!

2022-03-29 14:22 UTC, euijinkk commented on src/ts/domain/Product.ts
> +export default class ProductImpl implements Product {
아하,, 인터페이스는 필요없는 것 같아, 모두 없앴습니다 ㅎㅎ 
interface를 중심으로 Connect 를 사용할 수도 있겠네요.
의견 감사합니다!

2022-03-29 14:24 UTC, euijinkk commented on src/ts/ui/ProductManagementUI/ProductAdditionUI.ts
> +    };
아하, 

as를 사용하지 않으려면

```javascript
if (!($$formElements.namedItem('name') is instanceof HTMLInputElement) return;

if (!($$formElements.namedItem('price') is instanceof HTMLInputElement) return;

if (!($$formElements.namedItem('quantity') is instanceof HTMLInputElement) return;
```

이렇게 3번 각각 타입 내로윙을 해주어야하는데, 코드가 너무 길고 복잡하고, HTMLInputElement라는 것을 확신할 수 있기 때문에... as를 사용했다는것입니다!

2022-03-29 14:26 UTC, euijinkk commented on src/ts/constants/index.ts
> +  }원 이상 ${PRICE_RULE.MAX.toLocaleString()}원 이하여야 하며, ${
아하, 
toLocaleString 기능에다가, 소수점 대응, 유연한 포맷팅까지 고려하여 유틸화하면 좋을 것 같다는 의견이군요! 

생각 못해봤어요!
의견 감사합니다!

2022-03-29 14:28 UTC, euijinkk commented on src/ts/__test__/validator.test.ts
> +    );
1. 테스트 코드 자체가 명세가 되기도 하고, 
2. 유지보수의 대상이기 때문에, 

테스트 코드가 읽기 쉬어야 한다는 점, 좋은 의견인 것 같습니다.
현재는 validateProductInfo 하나로 검증하고 있기 때문에, 어디에서 에러가 났는지 명확히 확인이 어려울 것 같습니다. 

2단계에서 메소드 단위로 검증해보도록 하겠습니다!

시원하게 해결된 것 같아요!!! 너무 감사합니당~!~

2022-03-29 14:32 UTC, euijinkk commented on src/ts/ui/ProductManagementUI/ProductAdditionUI.ts
> +    };
아하 그렇구나! 
제가 임의로 사용한 것입니다. 
못 보셨다고 하니, 보통 이렇게 사용하지는 않나 보군요!

복수형 s가 붙기 때문에 이미 의미 전달이 된다고 판단하고, $ 하나로 처리하는 것이 좋을 것 같습니다.

수정했습니다 ㅎㅎ

2022-03-29 15:22 UTC, euijinkk commented
코멘트 감사합니다!!

수정 사항 반영했고,
그대로 유지한 부분은 2단계에 한번 시도해보겠습니다.

감사합니다!!

2022-03-30 11:39 UTC, inwalter99 commented on src/ts/ui/ProductManagementUI/ProductAdditionUI.ts
> +    };
> 못 보셨다고 하니, 보통 이렇게 사용하지는 않나 보군요!

ㅋㅋ 더 자세히 말하자면 리액트에서는 DOM 을 직접 조작할 일이 없어 그럴 수도 있습니다..ㅎ 컨벤션이라는 건 정답은 없고 서로간의 약속이니 사실 편한대로(?) 일관성만 지킨다면 어떻게 하든 상관없다고 생각합니다.

2022-03-30 11:41 UTC, inwalter99 approved these changes
수고하셨습니다! 머지하도록 할게요!
2단계가 기다려집니다!

2022-03-30 11:41 UTC, merged