[1단계 - 자판기] 안(안수진) 미션 제출합니다.
woowacourse/javascript-vendingmachine pull request #31
Opened 2022-03-27 07:46 UTC by jin7969

안녕하세요. 영범님!! 이번 자판기 미션을 제출하는 '안'이라고 합니다  😆😄

### [🚀 데모 페이지](https://jin7969.github.io/javascript-vendingmachine/)

### 구현 내용
- model, view, controller 를 분리하여 구현을 하였으며, 커스텀이벤트를 사용하여 view와 controller 를 연결하였습니다.
- 처음으로 타입스크립트를 사용하여 model에 적용해 보았습니다.
- route를 이용하여 각 메뉴 클릭시 해당 내용이 보이도록 적용하였습니다.

### 질문 사항
- 현재 ts interface 파일을 따로 분리하여 작성하였습니다. 하지만 굳이 interface 파일을 따로 분리할 필요가 있는지 아니면,
범용적으로 사용하는 부분만 따로 만들어서 사용을하고, 특정 클래스에서만 사용되는 부분은 클래스 파일 안에 사용해도 괜찮은지 궁금합니다.

- try catch 문에서 전부 try 안에서 구현을 하였습니다. 변수 선언이나, try catch 가 필요하지 않는 부분은 밖에서 작성하는 것이 가독성 측면에서 괜찮다고 생각됩니다. 지금은 변수 선언만 해당되어 같이 있지만, 나중에 필요하지 않는 부분이 많이지면 따로 작성하는것이 낫다고 생각되는데 리뷰어님 의견이 궁금합니다!
```js
  try {
    const { amount } = e.detail;
    this.coin.setAmount(amount);
    this.chargeView.renderCurrentAmount(this.coin.getAmount());
    this.chargeView.resetChargeInput();
    this.chargeView.renderHaveCoins(this.coin.getCoins());
  } catch (error) {
    alert(error.message);
  }
```
리뷰 부탁드립니다!! 🙏

2022-03-29 03:42 UTC, youngbeomrhee requested changes
안님 안녕하세요 리뷰를 맡은 YB입니다 
커스텀 엘리먼트를 활용하고 전반적으로 깔끔한 구조로 기능을 구현해 주셨네요
다만 개선해 보시면 좋을 만한 사항들이 있어서 수정요청 드립니다

## 기능상 오류 (필수수정)
- 발생 시나리오 : 잔돈충전 메뉴 진입 -> 화면 새로고침 -> 10 입력 -> 구입 클릭 -> 10원 -4개, 50원 1개 등(랜덤이라 다양한 케이스)의 오류 발생
아래 테스트 케이스 보강과 연결되는 부분이지만 적절한 중간값을 넣을 경우는 예외상황을 확인하기 어려운 경우가 많습니다. 항상 경계값을 가지고 테스트를 해보시고 특히 랜덤함수를 활용하는 로직이라면 같은 케이스에 대해서도 충분히 많은 횟수를 반복해서 테스트 해봐야 합니다 (예: 구입금액 10원 입력 후 잔돈으로 변환 * n). 사람이 직접 하는건 효율성이 굉장히 떨어지므로 이런 경우에 테스트 코드의 활용이 필요해 집니다
- TS가 일부만 적용되어 있고 나머지는 JS로 작성되어 있습니다. 해당 미션이 TS에 대한 훈련도 포함되는만큼 나머지 코드도 변경요청 드립니다

## 개선 (가능한 범위 안에서 수정)
- Controller 하나에서 모든 기능을 처리하다보니 조금씩 비대해지고 있습니다. 분리해 보시면 좋을 것 같습니다
- 테스트코드 보강(코드 레벨에 코멘트 드렸습니다)

## 질문에 대한 답변 
> 현재 ts interface 파일을 따로 분리하여 작성하였습니다. 하지만 굳이 interface 파일을 따로 분리할 필요가 있는지 아니면, 범용적으로 사용하는 부분만 따로 만들어서 사용을하고, 특정 클래스에서만 사용되는 부분은 클래스 파일 안에 사용해도 괜찮은지 궁금합니다.
>> 말씀하신 것처럼 범용적으로 사용되는 경우만 하나의 공통의 파일에서 관리하고 특정 파일에만 적용되는 영역은 해당 파일에서 관리하는게 보다 나은 방식이라고 생각합니다

> try catch 문에서 전부 try 안에서 구현을 하였습니다. 변수 선언이나, try catch 가 필요하지 않는 부분은 밖에서 작성하는 것이 가독성 측면에서 괜찮다고 생각됩니다. 지금은 변수 선언만 해당되어 같이 있지만, 나중에 필요하지 않는 부분이 많이지면 따로 작성하는것이 낫다고 생각되는데 리뷰어님 의견이 궁금합니다!
>> try catch로 묶는건 에러가 발생할 가능성이 있는 부분으로 한정해서 묶고 그에 대한 에러처리를 명시하는게 보다 권장되는 방식일 것 같습니다. 예로 들어주신 변수선언의 경우는 try catch 안에 통으로 묶는 것 보다는 값이 넘어오지 않았을 경우를 대비해서 함수의 파라미터라면 기본값을 설정하거나, 선언과 동시에 초기화 한다면 OR연산자를 활용하는 등의 예외처리가 보다 적합할 것 같습니다

2022-03-29 03:42 UTC, youngbeomrhee commented on src/__tests__/productManage.test.js
> +import ProductManager from '../js/models/ProductManger.ts';
상세하게 테스트 케이스를 작성해 주셨네요 👍

2022-03-29 03:42 UTC, youngbeomrhee commented on src/css/index.css
> +  --color-white: #ffffff;
css 변수를 잘 활용해 주셨네요 👍

2022-03-29 03:42 UTC, youngbeomrhee commented on src/js/controller.js
> +    if (hash === '#!charge') {
같은 변수에 대해 값의 일치여부를 확인하고 있고 중복으로 조건에 해당하는 경우는 없다는 걸 문법적(if, else if, else, switch문 등)으로도 적용해주면 보다 가독성이 좋아지지 않을까요?

2022-03-29 03:42 UTC, youngbeomrhee commented on src/js/models/Coin.ts
> +  makeRandomCoins(amount: number): void {
요구사항의 핵심로직을 잘 파악하고 재귀를 사용해서 적절하게 잘 구현해 주셨네요 👍

2022-03-29 03:42 UTC, youngbeomrhee commented on src/js/index.ts
> +import Controller from './Controller.js';
실제 파일명은 소문자로 되어있는데요 오타인가요?

2022-03-29 03:42 UTC, youngbeomrhee commented on src/js/controller.js
> +import { SECTION_CONTAINER } from './constants/constants.js';
하나의 controller에서 모든 것을 구현하다보면 금새 해당 파일이 비대해질 것 같은데요
적절히 분리해보면 어떨까요?

2022-03-29 03:42 UTC, youngbeomrhee commented on src/js/views/ProductManageView.js
> +      if (target.classList.contains('modify-button')) {
다른 코멘트에서도 언급 드렸었지만 case 1, 2, 3 중에 하나에 해당하는 경우고 중복으로 해당되면 안되는 로직이라 문법적으로도 그런 의도를 보여주면 조금 더 가독성이 좋은 코드가 될 것 같습니다

2022-03-29 03:42 UTC, youngbeomrhee commented on src/js/views/ProductManageView.js
> +      name: selectedProduct.children[0].textContent,
저도 초반에 웹개발을 시작했을 때 편의성 때문에 DOM 구조에 의존하는 코드를 많이 작성했었는데요
문제는 요구사항이 바뀌면서 DOM의 구조가 바뀌는 일이 빈번하다보니 기존에 작동하던 영역이 작동하지 않는 경험을 많이 하게 되면서 현재의 DOM 구조에 의존하는 코드는 더이상 작성하지 않게 되었습니다
Vanilla JS로 작성하다보니 DOM을 핸들링하기 어려워서 나오는 구조라는건 이해하지만 현재 구조는 변경에 매우 취약하다는 점은 인지하시면 좋을 것 같습니다

2022-03-29 03:42 UTC, youngbeomrhee commented on src/__tests__/coins.test.js
> +import Coin from '../js/models/Coin.ts';
테스트 케이스가 보강되면 좋을 것 같습니다
현재 에러가 발생할 가능성이 높은 부분은 일정 금액만큼 랜덤하게 금액별 동전으로 바꾸는 로직일텐데요 그 부분에 대한 테스트가 누락되어 있습니다
그리고 경계값에 대한 테스트가 보완되었다면 사전에 기능오류를 발견할 수 있었을 것 같습니다 (예: 최소 10원 -> 가능, 그 이하 -> 불가능, 최대 -> 10만원 가능,  그 이상 -> 불가능)

2022-03-29 03:42 UTC, youngbeomrhee commented on src/js/views/ProductManageView.js
> +    this.$productNameInput = $('#product-name-input');
전역에서 사용될 변수를 특정 메서드에서 선언해서 사용하게 되면 전역에서 사용 가능한 변수가 한 눈에 보이지 않아서 가독성이 떨어지게 됩니다
자바스크립트라서 문법적으로는 가능한 구조지만 다른 언어 사용자들에게 단골로 비판받는 안티패턴이기도 합니다
한 눈에 확인할 수 있는 구조로 개선해 보시면 좋을 것 같습니다~

2022-03-31 07:54 UTC, jin7969 commented on src/js/controller.js
> +    if (hash === '#!charge') {
탭 메뉴가 3개로 한정되있기 떄문에 switch 문으로 변경하였습니다.
`case '#!manage':` 이렇게 case 로 지정을 하니 가독성이 좋아졌습니다!! 감사합니다 👍
https://github.com/woowacourse/javascript-vendingmachine/pull/31/commits/41ecf7f01d629e225114e1353e0bd1e6949ba3bf

2022-03-31 08:10 UTC, jin7969 commented on src/js/index.ts
> +import Controller from './Controller.js';
제 vscode 에서는 대문자로 되어있는데... 이상하네요 확인해보겠습니다.

2022-04-01 09:31 UTC, jin7969 commented on src/js/controller.js
> +import { SECTION_CONTAINER } from './constants/constants.js';
맞습니다! 2단계에서기능들이 추가 되면 복잡해지고 가독성이 좋지 않다고 생각되어
컨트롤러 파일을 분리하였습니다.

https://github.com/woowacourse/javascript-vendingmachine/pull/31/commits/31addab5e4d75265c14553effc3d2a88ce65ef86

2022-04-01 09:52 UTC, jin7969 commented on src/js/views/ProductManageView.js
> +      if (target.classList.contains('modify-button')) {
`target.classList.contains` 이 부분을 어떻게 하면 중복을 줄일 수 있을까 고민을 하였는데,,

`const className = target.classList.value;` 클래스 네임을 찾고 swith 문을 이용하면 되겠군요 감사합니닿ㅎ


https://github.com/woowacourse/javascript-vendingmachine/pull/31/commits/1d15a78ef572406ba0db8bddabc7733ef28af40f

2022-04-01 10:37 UTC, jin7969 commented on src/js/views/ProductManageView.js
> +      if (target.classList.contains('modify-button')) {
`target.classList.value;`  -> `const { className } = e.target;` 으로 수정하였습니다

2022-04-01 13:12 UTC, jin7969 commented on src/js/views/ProductManageView.js
> +      name: selectedProduct.children[0].textContent,
1. 수정 버튼 자체에 data 속성으로 이름,가격,수량 을 담아 놓고 사용하였습니다.
```js
// template

<button 
  class="modify-button" 
  type="button" 
  data-name=${name} 
  data-price=${price} 
  data-quantity=${quantity}>수정
</button>

// 해당 상품 정보

const product = {
  name: selectedProductButton.dataset.name,
  price: selectedProductButton.dataset.price,
  quantity: selectedProductButton.dataset.quantity,
};
```

2. 인풋 하나하나 id 값은 주고, 셀렉팅을 해서 밸류 값을 가져오도록 하였습니다.

```js
// before

const product = {
  name: selectedProduct.children[0].firstChild.value.trim(),
  price: selectedProduct.children[1].firstChild.valueAsNumber,
  quantity: selectedProduct.children[2].firstChild.valueAsNumber,
};

// after

const product = {
  name: selectedProduct.querySelector('#modify-name').value.trim(),
  price: selectedProduct.querySelector('#modify-price').valueAsNumber,
  quantity: selectedProduct.querySelector('#modify-quantity').valueAsNumber,
};
```

위에 2가지 방식에 대해서 YB님은 어떻게 생각하시나요??

2022-04-01 14:51 UTC, jin7969 commented on src/js/views/ProductManageView.js
> +    this.$productNameInput = $('#product-name-input');
저도 동의합니다!!
하지만 현재 라우트구조로 인해 상품관리 탭이 render 되기전에 전역변수로 선언을 하면 오류가 발생하게 되어
메서드안에서 사용을 하였습니다. 
생각해 보았지만 어려움이 있어 질문드립니다. 혹시 다른 방법이 있을까요??

사소한 부분이지만 `initManageDOM()` 메서드를 위치를 맨위로 올려두었습니다.

2022-04-01 17:13 UTC, jin7969 commented on src/__tests__/coins.test.js
> +import Coin from '../js/models/Coin.ts';
수정하였습니다 ㅎ

2022-04-01 17:39 UTC, jin7969 commented
안녕하세요 YB님~~ 
늦어서 죄송합니다!! 🙏


> 잔돈충전 메뉴 진입 -> 화면 새로고침 -> 10 입력 -> 구입 클릭 -> 10원 -4개, 50원 1개 등(랜덤이라 다양한 케이스)의 오류 발생

무작위로 동전을 만들어 주는 로직을 변경하여 수정하였습니다!
또한, 테스트 케이스를 보강하여 작성하였습니다.
<br>

> Controller 하나에서 모든 기능을 처리하다보니 조금씩 비대해지고 있습니다. 분리해 보시면 좋을 것 같습니다

2단계에서 요구사항이 추가되면 비대해지고 가독성이 좋지 않아 controller 파일을 분리 하였습니다.
<br>

> input 증가, 감소시 입력 가능한 단위(예: 10원)가 정해져 있는데 Spinner(위, 아래 버튼)의 단위는 1씩입니다. 사용성을 생각해서 입력 가능한 단위로 조절하면 좋을 것 같습니다.

이런 부분은 확인하지 못하였네요 ㅠㅠ 사용성을 위하여 input 속성에 `step=10` 추가 하였습니다. 
<br>

> TS가 일부만 적용되어 있고 나머지는 JS로 작성되어 있습니다. 해당 미션이 TS에 대한 훈련도 포함되는만큼 나머지 코드도 변경요청 드립니다

타입스크립트는 적용하지 못하였습니다ㅠ  ui 에는 적용하는 것이 어려움이 많아 학습을 한 뒤 2단계에서 수정해도 괜찮을까요??
<br>

나머지 코멘트에 대해서도 수정을 완료하였습니다 ㅎㅎ

2022-04-02 16:48 UTC, jin7969 commented on src/js/index.ts
> +import Controller from './Controller.js';
controller 파일을 나누면서 자연스레 해결하였습니다!

2022-04-03 11:44 UTC, youngbeomrhee commented on src/js/index.ts
> +import Controller from './Controller.js';
예 파일명을 변경할 때 대소문자만 변경하는건 적용되지 않는 경우가 많아서 그런 경우라면 파일명의 임의의 문자를 넣어서 변경하고 그 이후에 다시 한 번 더 원래 파일명으로 변경하면 원하는대로 대소문자 변경이 가능해지니 참고하시면 좋을 것 같습니다
예) controller -> Controller_ -> Controller

2022-04-03 12:20 UTC, youngbeomrhee commented on src/js/views/ProductManageView.js
> +      name: selectedProduct.children[0].textContent,
첫 번째 방식으로도 충분히 필요한 값을 전달할 수 있어서 해당 방식이 더 낫다고 보고요
두 번째 방식은 추가적인 dom에 대한 탐색이 필요해서 성능과 안정성 면에서 첫 번째 방식보다는 못한 것 같아요
현재 구조에서는 이번에 적용하신 첫 번째 방식으로 충분히 개선된 것 같습니다

2022-04-03 12:22 UTC, youngbeomrhee commented on src/js/views/ProductManageView.js
> +    this.$productNameInput = $('#product-name-input');
꼭 선언과 동시에 할당해야 되는건 아니니까요
가장 간단하게는 상단부에는 변수를 선언만 해두고 실제 사용되는 시점에 할당하면 될 것 같네요~

2022-04-03 12:46 UTC, youngbeomrhee approved these changes
안님 안녕하세요 코드 개선하느라 고생 많으셨습니다
리뷰드린 부분과 그 외에 개별적으로 개선해주신 사항들 확인했습니다
몇 가지 추가 개선사항은 코드레벨에 남겨드렸으니 확인 후에 Step2 구현에 적용해 보시면 좋을 것 같습니다
TS 변환에 어려움을 겪으시는건 충분히 이해하지만 어차피 실무에서 곧 겪게될 일들이라 Step2 구현하실 때 최대한 적용해 보시면 좋을 것 같습니다
그럼 Step2에서 뵙겠습니다~

2022-04-03 12:46 UTC, youngbeomrhee commented on src/__tests__/coins.test.js
> +  it('최소 10원까지 잔돈 충전을 할 수 있다.', () => {
테스트 케이스 보강과 함께 에러도 수정된 것 확인했습니다 👍

2022-04-03 12:46 UTC, youngbeomrhee commented on src/__tests__/coins.test.js
> +      return acc + cur * [500, 100, 50, 10][idx];
만약 요구사항이 1000원 단위도 거스름돈에 포함하기로 변경되었다면 이 테스트 코드는 수정없이 원래의 기능을 잘 수행할 수 있을까요?
어떤 형식이었다면 방금 말씀드린 요구사항 변화에도 대응할 수 있었을까요?

2022-04-03 12:46 UTC, youngbeomrhee commented on src/__tests__/coins.test.js
> +  it('100,000원 미만으로 잔돈 충전을 할 수 없다.', () => {
테스트에 대한 설명이 조금 잘못된 것 같네요

2022-04-03 12:46 UTC, youngbeomrhee commented on src/js/controller/Charge.js
> +import Coin from '../models/Coin.ts';
확실히 코드가 분리되니 구조가 한 눈에 보이네요 고생하셨습니다 👍

2022-04-03 12:46 UTC, youngbeomrhee commented on src/js/controller/ProductManage.js
> +    switch (hash) {
기존 코드처럼 다 읽지 않아도 한 눈에 로직이 읽히네요 👏

2022-04-03 12:46 UTC, youngbeomrhee commented on src/js/models/Coin.ts
> +      if (currentAmount >= COIN.UNIT_LIST[3]) {
이 부분도 일전의 코멘트와 동일한 개선점이 보입니다 
if문을 개별적으로 나열하는 경우는 if문마다 다른 케이스를 테스트하는 경우인데 내부 로직을 보면 세 가지 조건 중 하나에만 속할 수 있고 그 외의 조건에는 속하면 안되는 구조인게 맞나요? 
그런 경우라면 if () {} else if () {}등으로 그런 제약사항을 문법적으로도 표현해주면 코드의 가독성이 한결 좋아질 것 같습니다

2022-04-03 12:46 UTC, merged

2022-04-03 13:06 UTC, jin7969 commented on src/js/views/ProductManageView.js
> +      name: selectedProduct.children[0].textContent,
감사합니다 !!

2022-04-03 13:16 UTC, jin7969 commented on src/js/views/ProductManageView.js
> +    this.$productNameInput = $('#product-name-input');
혹시 이렇게 사용할 수 있다는 말씀일까요??
맞다면 단지 '가독성' 때문에 이렇게 하는게 좋을거 같다는 말씀인가요?? 
```js
export default class ProductManageView {
  constructor() {
    this.$productNameInput = '';
    this.$productPriceInput = '';
    this.$productQuantityInput = '';
    this.$productTbody = '';
  }

  initManageDOM() {
    this.$productNameInput = $('#product-name-input');
    this.$productPriceInput = $('#product-price-input');
    this.$productQuantityInput = $('#product-quantity-input');
    this.$productTbody = $('#product-tbody');

    this.#bindMangeEvent();
  }

```

2022-04-03 13:29 UTC, jin7969 commented on src/__tests__/coins.test.js
> +      return acc + cur * [500, 100, 50, 10][idx];
제가 생각을 제대로 안하고 작성을 하였네요ㅠ 짚어 주셔서 감사합니다.🙏
이런식으로 동전 단위를 상수에서 가져와서 사용하였습니다.
```js
const coin = new Coin();
const amount = 1000;
coin.setAmount(amount);
const coinValues = Object.values(coin.getCoins());
const totalAmount = coinValues.reduce((acc, cur, idx) => {
  return acc + cur * COIN.UNIT_LIST[idx];
}, 0);
expect(coin.getAmount()).toEqual(totalAmount);
```

2022-04-03 13:31 UTC, jin7969 commented on src/__tests__/coins.test.js
> +  it('100,000원 미만으로 잔돈 충전을 할 수 없다.', () => {
수정하였습니다.

2022-04-03 14:48 UTC, jin7969 commented on src/js/models/Coin.ts
> +      if (currentAmount >= COIN.UNIT_LIST[3]) {
else if 와 else 는 지양해야 한다 라고 생각을 했었습니다.
하지만 기존코드와 비교 하였을 때, else if 가 더 낫다고 생각되어 수정하였습니다.
코드에는 정답이 없네요 ㅠ 상황에 따라 적절하게 사용하겠습니다 ㅎ

2022-04-09 11:34 UTC, youngbeomrhee commented on src/js/views/ProductManageView.js
> +    this.$productNameInput = $('#product-name-input');
예 constructor 혹은 클래스 선언 상단에 변수를 모으는게 좋을 것 같습니다