[1단계 - 자판기] 민초(홍영민) 미션 제출합니다.
woowacourse/javascript-vendingmachine pull request #32
Opened 2022-03-27 08:52 UTC by jswith

### 1. 공통

- [x] Interface 또는 type을 이용하여, 주요 도메인 객체의 타입을 정의하고 설계한다.

### 2. 라우팅 기능

- [x] Browser History Api를 이용하여 SPA처럼 라우팅을 적용한다.
  - [x] 매번 페이지를 로드 하는 것이 아닌, 히스토리를 관리하고, 페이지를 url에 따라 동적으로 렌더링한다.
- [x] 상품 관리, 잔돈 충전, 상품 구매 페이지는 모두 동적으로 렌더링해야 한다.

### 3. 상품 관리 탭

#### UI

- [x] 상품 관리탭은 자판기가 보유하고 있는 상품을 추가하는 기능을 수행한다.
- [x] 최초 상품 목록은 비워진 상태이다.
- [x] 관리자가 상품을 추가하면 상품 현황이 업데이트된다.
- [x] 수정 시 상품명, 가격, 수량 정보 영역 자체가 인풋 영역으로 변경된다.
- [x] 관리자가 상품을 수정하면 상품 현황이 업데이트된다.
- [x] 삭제 시 confirm을 활용하여 사용자에게 다시 한 번 확인한다.
- [x] 관리자가 상품을 삭제하면 상품 현황이 업데이트된다.

#### Domain

- [x] 상품명은 최대 10글자까지 가능하다.
- [x] 상품 가격은 100원부터 시작하며, 최대 10,000원까지 가능하다. 그리고 10원으로 나누어 떨어져야 한다.
- [x] 한 제품당 수량은 최대 20개까지 넣을 수 있다.
- [x] 추가에 성공한 상품은 localStorage에 저장한다.
- [x] localStorage에 저장된 상품이 있을 경우 가져온다.

#### UI + Domain

- [x] 상품명, 가격, 수량을 입력해 상품을 추가할 수 있다.
- [x] 관리자는 추가한 상품을 수정, 삭제할 수 있다.

#### 예외

- [x] [예외] 상품명이 중복되는 경우
- [x] [예외] 상품명이 공백인 경우
- [x] [예외] 상품명이 10글자를 초과한 경우
- [x] [예외] 상품 가격이 100원 미만이거나 10,000원을 초과하는 경우
- [x] [예외] 상품 가격이 10원으로 나누어 떨어지지 않는 경우
- [x] [예외] 상품 가격이 공백인 경우
- [x] [예외] 상품 수량이 1개 미만이거나 20개를 초과한 경우
- [x] [예외] 상품 수량이 공백인 경우

### 4. 잔돈 충전 탭

#### UI

- [x] 잔돈 충전탭은 자판기가 보유할 금액을 충전하는 기능을 수행한다.

#### Domain

- [x] 잔돈 충전 탭에서 최초 자판기가 보유한 금액은 0원이며, 각 동전의 개수는 0개이다.
- [x] 잔돈은 10원으로 나누어 떨어지는 금액만 투입할 수 있다. 보유할 수 있는 최대 금액은 100,000원이다.
- [x] 자판기 보유 금액만큼의 동전이 무작위로 생성된다.
- [x] 자판기 보유 금액을 누적하여 충전할 수 있다. 추가 충전 금액만큼의 동전이 무작위로 생성되어 기존 동전들에 더해진다.
- [x] 잔돈은 localStorage에 저장한다.
- [x] localStorage에 저장된 잔돈이 있을 경우 가져온다.

#### UI + Domain

- [x] 잔돈 충전 입력 요소에 충전할 금액을 입력한 후, 충전하기 버튼을 눌러 자판기 보유 금액을 충전할 수 있다.

#### 예외

- [x] [예외] 충전할 금액이 공백인 경우
- [x] [예외] 금액이 0원 이하이거나 100,000원을 초과할 경우
- [x] [예외] (충전할 금액 + 현재 보유 금액)이 100,000원을 초과할 경우
- [x] [예외] 금액이 10원으로 나누어 떨어지지 않는 경우

### 테스트 요구사항

- [x] 비즈니스 로직에 대한 단위 테스트를 Jest로 작성한다.

2022-03-28 20:03 UTC, EungyuCho requested changes
안녕하세요 민초님! 리뷰어 아사입니다.
리뷰가 늦어져 죄송합니다 😭 
다음번엔 늦지않게 노력할게요!..

처음 데모 페이지를 확인해보는데 상품 정보를 수정할 때 focus된 input의 outline의 색상이 인상적이었어요. 👍 
프로젝트의 구조도 짜임새 있게 만들어주셨고 도메인 영역도 잘 분리해주셨네요. 테스트 케이스도 충분한거같아요. 그래서 리뷰는 요청해주신대로 네이밍과 ts위주로 피드백을 요청해주셔서 해당 부분을 위주로 코멘트를 남겨드렸어요. 

코멘트 확인부탁드릴게요!!
구현하시느라 고생많으셨어요!

2022-03-28 20:03 UTC, EungyuCho commented on src/__test__/app.test.ts
> +const addProduct = (name: string, price: number, quantity: number) => {
```suggestion
const addProduct = ({name, price, quantity}: IProduct) => {
```
인자를 [객체형태](https://github.com/qkraudghgh/clean-code-javascript-ko#%ED%95%A8%EC%88%98functions)로 받아봅시다!~ 
테스트에 인자를 넣을때도 어떤 데이터인지 직관적으로 알 수 있어요!

2022-03-28 20:03 UTC, EungyuCho commented on src/__test__/app.test.ts
> +    addProduct('잡초', 1000, 10);
```suggestion
  const weed = {
    name: '잡초',
    price: 1000,
    quantity: 10,
  };

  test('상품을 추가할 수 있다.', () => {
    addProduct(weed);

    expect(findProduct(weed.name).name).toBe(weed.name);
  });

  test('특정 상품을 수정할 수 있다.', () => {
    addProduct(weed);
```
위에 코멘트를 반영하신다면 보다 더 직관적인 테스트를 작성하실 수 있을거에요!

2022-03-28 20:03 UTC, EungyuCho commented on src/__test__/app.test.ts
> +      VendingMachine.instance.charge(200000);
```suggestion
      VendingMachine.instance.charge(CONFIGURATION.MAX + 1);
```
설정값을 직접 활용하시는게 좋아요 👀

2022-03-28 20:03 UTC, EungyuCho commented on src/__test__/app.test.ts
> +    expect(VendingMachine.instance.amount.getAmount()).toBe(1000);
이러한 충전금액도 임계값을 기준으로 테스트하는걸 권장해드릴게요!
```suggestion
    VendingMachine.instance.charge(CONFIGURATION.MAX);

    expect(VendingMachine.instance.amount.getAmount()).toBe(CONFIGURATION.MAX);
```

2022-03-28 20:03 UTC, EungyuCho commented on src/domain/Product.ts
> +  constructor(product: Product, id = Math.random().toString(36).substring(2, 9)) {
id를 dataset에 활용해주시려고 설정해주셨네요 👍 👍 
도메인을 관리하는데 best라고 생각해요 🙂

2022-03-28 20:03 UTC, EungyuCho commented on src/validator/index.ts
> +};
이러한 상품에 관련된 데이터의 검증들은 Product 클래스(도메인)에서 해보고 에러를 throw해주면 어떨까요?
도메인에 올바른 데이터 생성에 대한 책임을 지게 validation 역할을 도메인에서 생성해보는게 좋을 거 같아요

2022-03-28 20:03 UTC, EungyuCho commented on src/router.ts
> +  history.pushState({ pathname }, '', pathname);
pathname이 null일때의 처리가 필요해요.

다른 탭이 눌린 상태에서 버튼 사이에 있는 빈 영역을 클릭하면 null이 들어가면서 이전 ui가 사라져요

2022-03-28 20:03 UTC, EungyuCho commented on src/router.ts
> +  history.pushState({ pathname }, '', pathname);
같은 버튼을 연속해서 클릭하면 해당 횟수만큼 history에 쌓여서 이전으로 돌아가도 동일한 ui만 반복해서 호출하고 있어요

2022-03-28 20:03 UTC, EungyuCho commented on src/css/index.css
> +}
현재 미션에서는 크게 문제가 없을거라 생각되지만 태그네임을 기준으로 css를 적용하는건 지양하시는게 좋아요 👀

2022-03-28 20:03 UTC, EungyuCho commented on src/router.ts
> +  const prevs = routers.filter((route) => route.path !== path);
```suggestion
  const currentComponent = routers.find((route) => route.path === path)?.component ?? $('product-management');
  const prevRoute = routers.filter((route) => route.path !== path);
```
변수명은 정확하게 적어주는게 좋을거같아요!

2022-03-28 20:03 UTC, EungyuCho commented on src/ui/ProductManagement.ts
> +    }
switch문이 더 가독성이 좋을수도 있겠다 싶네요 🙂

2022-03-28 20:03 UTC, EungyuCho commented on src/domain/VendingMachine.ts
> +      const target = this.products.find((product) => product.name === targetName);
```suggestion
      const currentProduct = this.products.find((product) => product.name === targetName);
```
현재 업데이트하는 상품이니 이 네이밍이 더 적합하다고 생각해요!

2022-03-28 20:03 UTC, EungyuCho commented on .cz-config.js
> +module.exports = {
cz.. 세팅하느라 고생하셨어요! 👍

2022-03-28 20:03 UTC, EungyuCho commented on src/ui/ProductManagement.ts
> +    const quantity = values[2];
```suggestion
    const [name, priceWithSeparator, quantity] = [...item.getElementsByTagName('td')].slice(0, 3).map((td) => td.textContent);

    const price = deleteSeparator(priceWithSeperator);
```
3번 배열이 들어온다고 확신할 수 있다면 이렇게도 해볼 수 있겠네요

2022-03-28 20:03 UTC, EungyuCho commented on src/validator/index.ts
> +    return filterArr.some((product) => product.name === name);
filterArr도 괜찮지만 filteredProducts가 더 맞는거같아요

2022-03-28 20:03 UTC, EungyuCho commented on src/domain/Coin.ts
> +  10: number = 0;
```suggestion
class Coin {
  500 = 0;
  100 = 0;
  50 = 0;
  10 = 0;
```
외부에서 활용할 일 없는 인터페이스라면 implement할 필요없을거같아요.
클래스 내부에서도 초기화를 0이라는 number 타입으로 추론을 해줘서 명시할 필요는 없을거같네요

2022-03-28 20:03 UTC, EungyuCho commented on src/css/product-manage-tab.css
> +}
세상에.. 보고 놀랬어요 예쁘게 구현해주셨네요!

2022-03-29 22:11 UTC, jswith commented on src/__test__/app.test.ts
> +const addProduct = (name: string, price: number, quantity: number) => {
오오 interface를 이런식으로 활용할 수도 있었네요!!

2022-03-29 22:16 UTC, jswith commented on src/css/product-manage-tab.css
> +}
페어랑 재미있게 코딩하고자 구현했던 부분인데 예상 외(?)의 반응이라 감사합니다! ㅋㅋㅋㅋㅋ

2022-03-30 00:39 UTC, jswith commented on src/__test__/app.test.ts
> +    expect(VendingMachine.instance.amount.getAmount()).toBe(1000);
알면서도 자꾸 까먹네요 ㅎㅎ
임계값 소리내어 20번 외쳤습니다..

2022-03-30 00:44 UTC, jswith commented on src/__test__/app.test.ts
> +      VendingMachine.instance.charge(200000);
임계값에서 +1 사소하지만 좋은 방법인 것 같습니다 😯 상수 + 1 하는 건 상상도 못했었는데 하나 배워갑니다! 👏

2022-03-30 05:06 UTC, jswith commented on src/__test__/app.test.ts
> +    addProduct('잡초', 1000, 10);
오호 내부에서 객체를 만들어서 인자로 넣어주는 방법도 괜찮네요!

2022-03-30 06:03 UTC, jswith commented on src/validator/index.ts
> +    return filterArr.some((product) => product.name === name);
넵 너무 일반적으로 적은 것 같네요!

2022-03-30 06:08 UTC, jswith commented on src/domain/VendingMachine.ts
> +      const target = this.products.find((product) => product.name === targetName);
다른 부분은 `~Product` 인데 이 부분만 네이밍이 달랐네요!!

2022-03-30 06:11 UTC, jswith commented on src/router.ts
> +  const prevs = routers.filter((route) => route.path !== path);
넵~ 변수명을 정확하게 적어줘야 어떤 역할울 허눈 변수인지 바로 파악할 수 있을 것 같습니다!

2022-03-30 08:15 UTC, jswith commented on src/domain/Coin.ts
> +  10: number = 0;
외부 활용 여부에 따라 implement를 결정할 수도 있겠네요!
위 사례의 숫자값 초기화와 같이 타입 추론이 명백한 경우, 리뷰어님께서는 보통 타입을 명시하지 않는 편이신가요?

2022-03-30 08:59 UTC, jswith commented on src/ui/ProductManagement.ts
> +    const quantity = values[2];
price 변수만 함수 호출이 필요해서 어떻게 리팩토링 할 수 있을지 고민했었는데
map으로 한 번 돌린 다음에 price만 따로 deleteSeperator 하는 방법도 있었네요~!
원래 고민했던 방식은 map 돌리면서 if 문으로 price일 경우에만 deleteSeperator 하는 방식이었는데 뭔가 지저분한 것 같아 지우고 위와 같은 코드를 작성했었습니다~ ㅠㅠ

2022-03-30 09:03 UTC, jswith commented on src/ui/ProductManagement.ts
> +    }
넵 action에 따라 분기하는 부분이라 저도 switch문이 더 가독성이 좋다고 생각합니다!

2022-03-30 09:23 UTC, jswith commented on src/css/index.css
> +}
넵 규모가 커지면 스타일이 충돌할 가능성이 증가할 것 같네요! 요 부분은 step2에서 기능 확장하면서 수정해보도록 하겠습니다!

2022-03-30 10:30 UTC, jswith commented on src/router.ts
> +  history.pushState({ pathname }, '', pathname);
type이 버튼인 경우에만 이벤트가 발생하도록 처리했습니다!

2022-03-30 10:31 UTC, jswith commented on src/router.ts
> +  history.pushState({ pathname }, '', pathname);
이 부분은 캐치하지 못했었네요! pathname이 동일한 경우 early return 하도록 처리했습니다!

2022-03-30 11:48 UTC, jswith commented on src/__test__/app.test.ts
> +const addProduct = (name: string, price: number, quantity: number) => {
반영 링크입니다! [99dcb88](https://github.com/woowacourse/javascript-vendingmachine/pull/32/commits/99dcb880b05a9ecc828ce945bd8f1b390859fe57)

2022-03-30 11:48 UTC, jswith commented on src/__test__/app.test.ts
> +    addProduct('잡초', 1000, 10);
반영 링크입니다! [99dcb88](https://github.com/woowacourse/javascript-vendingmachine/pull/32/commits/99dcb880b05a9ecc828ce945bd8f1b390859fe57)

2022-03-30 11:48 UTC, jswith commented on src/__test__/app.test.ts
> +      VendingMachine.instance.charge(200000);
반영 링크입니다! [99dcb88](https://github.com/woowacourse/javascript-vendingmachine/pull/32/commits/99dcb880b05a9ecc828ce945bd8f1b390859fe57)

2022-03-30 11:48 UTC, jswith commented on src/__test__/app.test.ts
> +    expect(VendingMachine.instance.amount.getAmount()).toBe(1000);
반영 링크입니다! [99dcb88](https://github.com/woowacourse/javascript-vendingmachine/pull/32/commits/99dcb880b05a9ecc828ce945bd8f1b390859fe57)

2022-03-30 11:49 UTC, jswith commented on src/validator/index.ts
> +};
throw 해주는 부분을 domain 내부로 이동하였습니다. 아사님이 말씀하신 부분이 이 부분이 맞는지 궁금합니다!
반영 링크입니다! [a319abe](https://github.com/woowacourse/javascript-vendingmachine/pull/32/commits/a319abe6e64cdb61fa8dcca247c5f800e64e7218)

2022-03-30 11:49 UTC, jswith commented on src/router.ts
> +  history.pushState({ pathname }, '', pathname);
반영 링크입니다! [dcecd9b](https://github.com/woowacourse/javascript-vendingmachine/pull/32/commits/dcecd9b59b774c2434fa1e81c37e8a3dc89d80c8)

2022-03-30 11:49 UTC, jswith commented on src/router.ts
> +  history.pushState({ pathname }, '', pathname);
반영 링크입니다! [dcecd9b](https://github.com/woowacourse/javascript-vendingmachine/pull/32/commits/dcecd9b59b774c2434fa1e81c37e8a3dc89d80c8)

2022-03-30 11:50 UTC, jswith commented on src/router.ts
> +  const prevs = routers.filter((route) => route.path !== path);
반영 링크입니다! [082edc3](https://github.com/woowacourse/javascript-vendingmachine/pull/32/commits/082edc31363bd66f8a6cbf67f9708f3fd981d97d)

2022-03-30 11:50 UTC, jswith commented on src/domain/VendingMachine.ts
> +      const target = this.products.find((product) => product.name === targetName);
반영 링크입니다! [082edc3](https://github.com/woowacourse/javascript-vendingmachine/pull/32/commits/082edc31363bd66f8a6cbf67f9708f3fd981d97d)

2022-03-30 11:50 UTC, jswith commented on src/validator/index.ts
> +    return filterArr.some((product) => product.name === name);
반영 링크입니다! [082edc3](https://github.com/woowacourse/javascript-vendingmachine/pull/32/commits/082edc31363bd66f8a6cbf67f9708f3fd981d97d)

2022-03-30 11:50 UTC, jswith commented on src/ui/ProductManagement.ts
> +    }
반영 링크입니다! [dd24d8a](https://github.com/woowacourse/javascript-vendingmachine/pull/32/commits/dd24d8aa94b05b8d8660d98b487525665a9c504e)

2022-03-30 11:50 UTC, jswith commented on src/ui/ProductManagement.ts
> +    const quantity = values[2];
반영 링크입니다! [dd24d8a](https://github.com/woowacourse/javascript-vendingmachine/pull/32/commits/dd24d8aa94b05b8d8660d98b487525665a9c504e)

2022-03-30 11:51 UTC, jswith commented on src/domain/Coin.ts
> +  10: number = 0;
반영 링크입니다! [4b23e71](https://github.com/woowacourse/javascript-vendingmachine/pull/32/commits/4b23e715a101153e2c62cc72dbd01aa553624897)

2022-03-30 11:56 UTC, jswith commented
안녕하세요 아사님~
피드백 주신 부분 수정완료하여 리뷰 요청드립니다!
각 코멘트에 커밋 링크 남겨두었습니다!

2022-03-30 16:44 UTC, EungyuCho approved these changes
안녕하세요 민초님~

피드백 모두 확인했고 대부분 잘 반영해주셨어요! 하지만 피드백 드린 의도와 다르게 반영된 부분도 있어 해당 부분에 대해서는 추가로 코멘트 남겨드렸습니다.

추가 코멘트로 드린 부분은 다음 스텝에서 반영해주시면 되겠습니다
이번 미션 진행하시느라 고생하셨고 다음 스텝에서도 기대할게요! 🙂  

Approve하겠습니다~

2022-03-30 16:44 UTC, EungyuCho commented on src/domain/VendingMachine.ts
> +      this.validateProduct(product, this.products);
```suggestion
      this.validateProduct(product); // this.products는 이미 해당 클래스에서 가지고있어요 👀
```

2022-03-30 16:44 UTC, EungyuCho commented on src/domain/Product.ts
> +  }
```suggestion
  constructor(product: Product, id = Math.random().toString(36).substring(2, 9)) {
    this.validatePrice(product.price);
    this.validateQuantity(product.quantity);

    this.id = id;
    this.update(product);
  }

  update(product: Product) {
    this.validatePrice(product.price);
    this.validateQuantity(product.quantity);

    this.name = product.name;
    this.price = product.price;
    this.quantity = product.quantity;
  }

  private validatePrice(price: number) {
    if (price % CONFIGURATION.AMOUNT.UNIT !== 0) {
      throw new Error(ERROR_MESSAGE.INCORRECT_UNIT_PRODUCT_PRICE);
    }
  }

  private validateQuantity(price: number) {
    if (price > CONFIGURATION.QUANTITY.MAX) {
      throw new Error(ERROR_MESSAGE.INCORRECT_UNIT_PRODUCT_QUANTITY);  // required속성으로 필터링을해서 필요성에 의구심이 있긴하지만 예시를 위해 추가해봤어요 👀 
    }
  }
```
이렇게 도메인 내부에서 도메인 내부 데이터를 검증하면 좋을 것 같아 피드백을 드렸었어요!

2022-03-30 16:44 UTC, EungyuCho commented on src/templates.ts
> +          <input type="number" name="quantity" placeholder="수량" min="1" max="20" required />
required 속성이 있으니 상수를 꼭 넣어줍시다 🙂

2022-03-30 16:45 UTC, EungyuCho commented on src/domain/Coin.ts
> +  10: number = 0;
> 외부 활용 여부에 따라 implement를 결정할 수도 있겠네요! 위 사례의 숫자값 초기화와 같이 타입 추론이 명백한 경우, 리뷰어님께서는 보통 타입을 명시하지 않는 편이신가요?

저는 보통 명시하지 않는편입니다~
특히 저렇게 원시값을 직접 할당해 초기화하는 경우에는 더 필요성이 떨어진다고 생각해요!

2022-03-30 16:46 UTC, merged

2022-03-30 19:41 UTC, jswith commented on src/domain/Product.ts
> +  }
아 이런 방식이었군요! 😯