[1단계 - 자판기] 우디(우정민) 미션 제출합니다.
woowacourse/javascript-vendingmachine pull request #33
Opened 2022-03-27 13:39 UTC by greenblues1190

월터님 안녕하세요! 우디라고 합니다.
이번 미션 코드 리뷰 잘 부탁드립니다!

### [데모 페이지](https://woojeongmin.com/javascript-vendingmachine/)

## 구현 기능

- hash bang 방식을 이용해 라우팅을 구현했습니다.
- 상품명, 가격, 수량을 입력해 상품을 추가할 수 있습니다.
    - 상품명은 최대 10글자
    - 상품 가격은 100원 ~ 10,000원, 10원 단위
    - 수량은 최대 20개
    - **예외상황: 추가하는 상품명이 이미 존재하면 기존 상품의 가격을 입력받은 가격으로 갱신하고 수량을 추가했습니다.**
- 관리자는 추가한 상품을 수정, 삭제할 수 있습니다.
  - 상품 목록 각각의 수정 버튼을 클릭해 상품을 수정할 수 있습니다.
  - 수정 시 상품명, 가격, 수량 정보 영역 자체가 인풋 영역으로 변경됩니다.
  - **예외상황: 이미 존재하는 상품명으로 수정할 수 없도록 했습니다.**
  - 상품 목록 각각의 삭제 버튼을 클릭해 상품을 삭제할 수 있습니다.
  - 삭제 시 confirm을 활용하여 사용자에게 다시 한번 확인합니다.
- 잔돈 충전 입력 요소에 충전할 금액을 입력한 후, 충전하기 버튼을 눌러 자판기 보유 금액을 충전할 수 있습니다.
  - 투입 금액은 10원 단위
  - 보유할 수 있는 최대 금액은 100,000원
  - 자판기 보유 금액만큼의 동전이 무작위로 생성됩니다.
  - 자판기 보유 금액을 누적하여 충전할 수 있습니다. 추가 충전 금액만큼의 동전이 무작위로 생성되어 기존 동전들에 더해집니다.

## 구조

```mermaid
classDiagram
  Subject --> Observer
  HTMLElement <|-- Component
  Observer <|-- Component
  Subject <-- Component
  Subject <-- Item
  Subject <-- Coins
  Component <|-- 일반컴포넌트들
  Component <|-- 구독자컴포넌트들
  VendingMachine <-- 구독자컴포넌트들

  class Observer {
    notify()
  }
  
  class Subject {
    private static private: symbol
    private static subjects: Array~Subject~
    static currentObserver: Observer
    static observable<T>(obj: T): T
    static observe(target: Observer)
    static unobserve(target: Observer)
    private key: string
    private value: any
    private observers: Set~Observer~
    private updated: boolean
    constructor(key: string, initValue: any, checker: symbol)
    get() any
    set(newValue: any)
    observe(observer: Observer)
    unobserve(observer: Observer)
    checkUpdated()
    notify()
    toString() string
  }

  class VendingMachineState {
    <<interface>>
    items: Array~Item~
    coins: Coins
  }

  VendingMachineState <-- VendingMachine
  Item <-- VendingMachineState
  Coins <-- VendingMachineState

  class VendingMachine {
    state: VendingMachineState
    constructor(initItems: Array~Item~, initCoins: Coins)
    init(initItems: Item[], initCoins: Coins): void
    useStore(callback: Function): any
    addItem(item: Item) 
    updateItem(name: string, updatedItem: Item)
    removeItem(name: string)
    findItem(name: string): Item | null
    addCoin(amount: number)
    getTotalMoney(): number
  }

  class HTMLElement {
    connectedCallback()
    disconnectedCallback()
  }

  class Component {
    props
    state
    setProps()
    setup()
    render()
    clearDOM()
    template()
    beforeRender()
    afterRender()
    setState(newState)
    setEvent()
    addEvent(type, selector, callback)
  }

  class Item {
    <<interface>>
    name: string;
    price: number;
    quantity: number;
  }

  class Coins {
    <<interface>>
    10: number;
    50: number;
    100: number;
    500: number;
  }
```

### 도메인

- 이번 미션에서 처음 타입스크립트를 경험해보고 타입 체킹이 되는 부분이 편리하고 신기했습니다. 하지만 타입을 구현하는 부분에서 오버헤드가 크다는 느낌을 받았고 이번 미션같이 작은 프로젝트에는 불필요하다는 생각이 들었습니다.

### 상태 관리

- 옵저버 패턴을 사용했습니다. 컴포넌트가 템플릿 메소드 안에서 `vendingMachine.useStore()`로 items나 coins와 같은 subject를 참조하면 참조한 subject의 옵저버로 구독되도록 했습니다. subject의 상태 변화 시 구독한 컴포넌트들에게 통지하여 다시 렌더링되게 합니다.`HTMLElement`의 생명 주기 콜백을 사용해 DOM에서 컴포넌트가 제거될 때 구독을 해제하도록 했습니다.

- `requestAnimationFrame`으로 상태 변화가 있는지 체킹하며 상태 변화를 1 프레임마다 모아서 통지하는 방식으로 렌더링을 최적화했습니다. 이 부분 추가 후 jest에서 `requestAnimationFrame`을 지원하지 않아 테스트가 어려운 상태입니다.

### 컴포넌트

- html 마크업으로 컴포넌트를 구성할 수 있는 점이 사용하기 좋아보여 `CustomElements` API를 사용했습니다. 하지만 네이밍의 제약사항(하이픈으로 이어진 두 단어만 가능)과 타입스크립트를 사용할 때 es5로 트랜스파일링이 되지 않는 점이 불편했습니다.

- 렌더링을 innerHTML로 갈아끼우는 방식이기 때문에 diff 비교가 되지 않아 구현하기 힘든 부분들이 있었습니다. 예를 들어 새로운 상품을 추가하거나 상품을 수정하면 상품 목록 전체를 다시 렌더링해 다른 상품의 수정 상태가 사라집니다. DOM의 diff를 비교하여 해결할 수 있을 것 같아 DOM에 대해 찾아보고 있습니다.
  ![rerendering](https://media.giphy.com/media/NJGf8bTN5CeQlpER2x/giphy.gif)

2022-03-28 13:42 UTC, inwalter99 requested changes
안녕하세요 우디님 :) 반갑습니다.
먼저 코드 잘 봤습니다! 저한테 동일한 시간내에 이러한 구조로 작성해보라고 하면 절대 구현 못 할 거 같아요ㅎㅎ
custom-elements 에 대해서 잘 몰랐는데 덕분에 즐겁게 봤습니다!
우디님 코드 보면서 리액트나 뷰 같은 거 안쓰고도 충분히 서비스를 만들 수 있을 것 같다는 생각이 들었어요. 저도 나중에 우테코 끝나고 custom-elements 이용해서 사이드 플젝 하나 해보고 싶네요ㅎㅎ

본격적으로(?) 요구사항에 `Browser History Api를 이용하여 SPA처럼 라우팅을 적용한다.`  라는 내용이 있으니 Hash 를 이용한 라우팅보단 History Api 를 이용해서 라우팅을 해봤으면 좋겠습니다 ;) 다른 부분은 크게 수정할 부분이 없어보여 step2 가기전에 이 부분 먼저 수정해보면 어떨까요?

추가로 코멘트도 확인부탁드릴게요 ;)

2022-03-28 13:42 UTC, yongholeeme commented on src/utils/commons.ts
> +export const deepClone = <T>(obj: T): T => {
deepEqual, deepClone 는 직접 구현하신 코드인가용?

2022-03-28 13:42 UTC, yongholeeme commented on src/core/Component.js
> +  }
오오... https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements custom-elements 에 대해 어렴풋히 알고만 있었고 모르는 수준에 가까웠는데 꽤 유용한 메서드들을 많이 제공해주네요

2022-03-28 13:42 UTC, yongholeeme commented on src/domains/VendingMachine.ts
> +  constructor(initItems: Item[], initCoins: Coins) {
보통 함수를 동사형/명령형으로 작성해 initItems, initCoins 만 보면 각각을 초기화해주는 함수로 예상을 할 수 있어보이는데 다른 이름으로 수정해보는 건 어덜까요?

2022-03-28 13:42 UTC, yongholeeme commented on src/domains/VendingMachine.ts
> +  }
constructor 가 초기화 메서드라.. 따로 init 은 필요없어보여요!

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/constructor

2022-03-28 13:42 UTC, yongholeeme commented on src/domains/VendingMachine.ts
> +      : item;
https://github.com/woowacourse/javascript-vendingmachine/pull/33/files#diff-b7053f7b3626c605eb9d8a1e3b7c08603c1deec6a76ad3d29833f0748b622321R57 위에서 prevItem 이 있을 경우 return 이 되는 것 같은데 요기 로직이 실행될 수 있나용?

2022-03-28 13:42 UTC, inwalter99 commented on src/domains/VendingMachine.ts
> +      });
두 번째 객체는 따로 destructing 안해줘도 되지 않을까요??

```suggestion
      this.updateItem(prevItem.name, {
        ...prevItem,
        quantity: prevItem.quantity + item.quantity,
      });
```

2022-03-28 13:42 UTC, inwalter99 commented on src/domains/VendingMachine.ts
> +    return this.state.items.filter((item) => item.name === name)[0] || null;
filter 보단 find 를 쓰는 건 어떨까요? 로직상 문제는 없지만, 목적에 더 부합하는 메서드가 있다면 그걸 사용하는 게 좋다고 생각합니다 ;)

2022-03-28 13:42 UTC, inwalter99 commented on src/domains/VendingMachine.ts
> +    this.state.coins = updatedCoins;
reduce 를 활용할 생각도 하셨을 것 같은데 forEach 로 하신 이유가 있을까요? 뭐가 더 좋고 나쁘다의 질문보다는 순수한 궁금증입니다 ㅎ

2022-03-28 13:42 UTC, inwalter99 commented on src/utils/coinUtils.ts
> +} as const;
모두 0 인 객체가 좀 반복적으로 활용되는 것 같은데 분리해볼 수 있지 않을까요?

2022-03-28 13:42 UTC, inwalter99 commented on src/core/TableRow.js
> +export default class TableRow extends HTMLTableRowElement {
custom-elements 에서 extends 하기 위해서 별도로 TableRow 라는 걸 만들어주셨군요... 
Component 와 기본적으로 동일한데 이거 개선해볼 수 있을까여??

2022-03-28 13:42 UTC, inwalter99 commented on src/views/components/ItemRow.js
> +customElements.define('item-row', ItemRow, { extends: 'tr' });
custom-elements 에 대해서 잘 몰라 질문을 드립니다! extends 는 보통 어떤 경우에 사용되나요?

2022-03-28 13:42 UTC, inwalter99 commented on src/views/components/ItemRow.js
> +         isEditing
삼항연산자로 depth 가 깊어져 개인적으로 가독성이 떨어지는 것 같습니다. 혹시 early return 시켜보는 건 어떨까요?

```js
if(isEditing) {
  return ``
}

return ``
```

2022-03-28 13:48 UTC, inwalter99 commented
> 렌더링을 innerHTML로 갈아끼우는 방식이기 때문에 diff 비교가 되지 않아 구현하기 힘든 부분들이 있었습니다. 예를 들어 새로운 상품을 추가하거나 상품을 수정하면 상품 목록 전체를 다시 렌더링해 다른 상품의 수정 상태가 사라집니다. DOM의 diff를 비교하여 해결할 수 있을 것 같아 DOM에 대해 찾아보고 있습니다. 리뷰어님은 어떤 방식을 선택하실지 궁금합니다!

일단 현재 구조상 부모 컴포넌트가 렌더링되면 자연스럽게 하위 컴포넌트들도 렌더링이 되는 것처럼 보입니다. 컴포넌트를 분리한다고 하더라도 결국엔 상품 상태를 갖고 그리는 것이기 때문에 해결되지는 않겠죠. 결국 말씀해주신 것처럼 변하지 않는 DOM 에 대해서 다시 그리지 않아야 할 것 같은데 보통은 라이브러리들이 이 부분을 책임져주는 것 같습니다. 당연히 구현한다면 좋겠지만! (저도 정확히는 잘 몰라서 궁금은 하네요!!!!!) DOM 의 diff 까지 고려해보는 건 조금 멀리가는 게 아닐까 싶습니다..!

> 사실 저라면 저런 UX 를 채택하지 않을 것 같..ㅎ

2022-03-29 16:46 UTC, greenblues1190 commented on src/utils/commons.ts
> +export const deepClone = <T>(obj: T): T => {
네 상태에 ES6 자료형을 써보려고 Set, Map에 대한 깊은 비교, 복사 함수를 짰는데 결국 오브젝트로 상태 구현했네요 😅

2022-03-29 16:53 UTC, greenblues1190 commented on src/views/components/ItemRow.js
> +customElements.define('item-row', ItemRow, { extends: 'tr' });
```html
<table>
  ...
  <tbody>
    <item-row></item-row>
  <tbody>
</table>
```

위와 같이 사용을 하고 싶었는데 `{ extends: 'tr' }` 옵션 없이는 테이블이 로우로 인식을 못하더라구요. HTMLTableRowElement를 상속하고 무조건 저 옵션을 붙여야 테이블 로우가 제대로 렌더링이 되었습니다. 커스텀엘리먼츠에 제약사항이 많은 것 같아 좀 아쉽네요. 앞으로는 잘 사용하지 않을 것 같습니다.

2022-03-29 16:55 UTC, greenblues1190 commented on src/core/Component.js
> +  }
컴포넌트가 DOM에서 제거될 때 상태에 대한 구독을 해제하고 싶었는데 방법을 몰라서 고민하다가 생명 주기 콜백을 이용할 수 있을 것 같아 한번 써봤는데 유용하더라구요 😀

2022-03-29 17:05 UTC, greenblues1190 commented on src/domains/VendingMachine.ts
> +  constructor(initItems: Item[], initCoins: Coins) {
혼동의 여지가 있겠네요. 수정했습니다! 9b40a0b

2022-03-29 17:06 UTC, greenblues1190 commented on src/domains/VendingMachine.ts
> +  }
단위 테스트에서 각 테스트 전에 vendingMachine을 매번 생성하는 것보다 초기화 메서드를 호출하도록 했는데 굳이 그럴 필요가 없겠네요. constructor에서 초기화하도록 수정했습니다. 1f329f7

2022-03-29 17:07 UTC, greenblues1190 commented on src/domains/VendingMachine.ts
> +      });
그렇네요. suggestion 커밋하겠습니다!

2022-03-29 17:27 UTC, greenblues1190 commented on src/core/TableRow.js
> +export default class TableRow extends HTMLTableRowElement {
```html
<item-row>
  <tr>
    <td>...</td>
  <tr>
</item-row>
```

상품 목록의 각각의 상품을 Component 클래스를 상속받아 컴포넌트로 분리하여 위와 같이 작성을 하면 table row가 table 바깥으로 나가는 이슈가 있었습니다.

```html
<tr is="item-row>
  <td>...</td>
</tr>
```
현재 커스텀 컴포넌트를 사용하는 구조에서 table row를 컴포넌트로 분리하고 table 태그 내에서 정상적으로 보여주기 위해서는 HTMLTableRowElement를 상속받는 컴포넌트를 정의하여 위와 같이 작성하는 방법 밖에 없는 것 같습니다.

[웹 컴포넌트 API가 제약사항이 많은 것 같아](https://blog.logrocket.com/what-happened-to-web-components/#whypeoplearentusingwebcomponents) 2단계에서 다른 방식으로 컴포넌트를 구현하고 싶네요.

2022-03-29 17:34 UTC, greenblues1190 commented on src/domains/VendingMachine.ts
> +      : item;
현재 도달할 수 없는 코드를 리팩터링하면서 월터님이 지적하신 조건문 안으로 넣고 깜빡하고 안지웠네요. 지적 감사합니다 😅 7fcc1c2

2022-03-29 17:53 UTC, greenblues1190 commented on src/domains/VendingMachine.ts
> +    this.state.coins = updatedCoins;
```javascript
Object.keys(this.state.coins).reduce(
  (updatedCoins: Coins, key) => {
    updatedCoins[key] = this.state.coins[key] + randomCoins[key];

    return updatedCoins;
  },
  {
    10: 0,
    50: 0,
    100: 0,
    500: 0,
  }
);
```

처음에 위와 같이 reduce를 사용했다가 세번째 줄 `updatedCoins[key] = this.state.coins[key] + randomCoins[key];`에서 [no-param-reassign](https://eslint.org/docs/rules/no-param-reassign) 린트 에러가 발생해서 바깥에 updatedCoins를 선언하고 forEach를 사용했습니다.

```javascript
const updatedCoins = Object.keys(this.state.coins).reduce(
  (next: Coins, key) => ({
    ...next,
    [key]: this.state.coins[key] + randomCoins[key],
  }),
  {
    10: 0,
    50: 0,
    100: 0,
    500: 0,
  }
);
```
코멘트 보고 찾아보니 스프레드를 활용하는 방법이 있었네요. 적용했습니다! ce64922

2022-03-29 17:54 UTC, greenblues1190 commented on src/domains/VendingMachine.ts
> +    return this.state.items.filter((item) => item.name === name)[0] || null;
find를 쓸 수 있었군요. 모르던 메소드라 그동안 filter만 사용했는데 좀 부끄럽네요 😅 ce64922

2022-03-29 18:01 UTC, greenblues1190 commented on src/views/components/ItemRow.js
> +         isEditing
if/else의 조건 분기에서는 무의식적으로 삼항연산자를 써왔는데 템플릿 문자열 내에서는 depth가 깊어지는 문제가 있었군요. 수정했습니다! 111d8ac

2022-03-29 18:12 UTC, greenblues1190 commented on src/utils/coinUtils.ts
> +} as const;
모든 값이 0인 Coins 객체 상수로 분리했습니다 317de84

2022-03-29 18:18 UTC, greenblues1190 commented
> 일단 현재 구조상 부모 컴포넌트가 렌더링되면 자연스럽게 하위 컴포넌트들도 렌더링이 되는 것처럼 보입니다. 컴포넌트를 분리한다고 하더라도 결국엔 상품 상태를 갖고 그리는 것이기 때문에 해결되지는 않겠죠. 결국 말씀해주신 것처럼 변하지 않는 DOM 에 대해서 다시 그리지 않아야 할 것 같은데 보통은 라이브러리들이 이 부분을 책임져주는 것 같습니다. 당연히 구현한다면 좋겠지만! (저도 정확히는 잘 몰라서 궁금은 하네요!!!!!) DOM 의 diff 까지 고려해보는 건 조금 멀리가는 게 아닐까 싶습니다..!
> 
> > 사실 저라면 저런 UX 를 채택하지 않을 것 같..ㅎ
> > 물론 편법(?)으로 각 항목마다 상태값을 두고 한다면 ..100% 까진 아니어도 구현가능할 것 같습니다

상품의 수정 상태를 건드리지 않을 수 있도록 구현하고 싶은 욕심이 나네요... 😓 말씀하신대로 현재 상태에서 컴포넌트의 구조를 DOM diff 비교 가능하게 수정하는 건 조금 멀리가는 것 같습니다.

2022-03-29 19:26 UTC, greenblues1190 commented
> 본격적으로(?) 요구사항에 `Browser History Api를 이용하여 SPA처럼 라우팅을 적용한다.` 라는 내용이 있으니 Hash 를 이용한 라우팅보단 History Api 를 이용해서 라우팅을 해봤으면 좋겠습니다 ;) 다른 부분은 크게 수정할 부분이 없어보여 step2 가기전에 이 부분 먼저 수정해보면 어떨까요?

webpack devServer에 historyApiFallback 옵션 true로 주어서 history api로 라우팅하도록 수정했습니다. 현재 pushState의 state에 빈 객체를 넣어주고 있는데 2단계에서 해당 히스토리의 컴포넌트 상태까지 보관하도록 구현하고 싶네요 🙂

2022-03-30 11:44 UTC, inwalter99 commented on src/views/components/ItemRow.js
> +         isEditing
템플릿 내에서 사용된다면 어쩔 수 없이 삼항연산자를 써야겠지만, 개인적으로 통으로 분기되는 경우는 나눠서 하는 걸 선호하는 편이라서 의견드려봤습니다!

2022-03-30 11:47 UTC, inwalter99 commented on src/domains/VendingMachine.ts
> +    this.state.coins = updatedCoins;
아.. 저는 혹시 가독성과 관련해서 forEach 를 사용하셨나 해서 질문드려봤습니다ㅋㅋ 다른 크루과 관련된 질문을 해서 갑자기 질문 드려봤어요 ㅎㅎ https://github.com/woowacourse/javascript-vendingmachine/pull/10#discussion_r837373582

2022-03-30 12:16 UTC, inwalter99 commented on src/core/TableRow.js
> +export default class TableRow extends HTMLTableRowElement {
ㅠㅠㅋ 기대됐는데 아쉽네요.. 이번 프로젝트에선 이렇게 중복이 발생하는 이슈만 있다면 변경되지 않고 계속 가면 어떨까 싶긴 합니다 ;)

2022-03-30 12:17 UTC, inwalter99 approved these changes
수고하셨습니다! 역시 2단계가 기다려집니다.
이번 스텝은 머지하도록 하겠습니다

2022-03-30 12:17 UTC, merged