[1단계 - 자판기] 병민(윤병인) 미션 제출합니다.
woowacourse/javascript-vendingmachine pull request #40
Opened 2022-03-28 08:58 UTC by airman5573

안녕하세요, 병민입니다 :D 

이번 미션 피드백 잘 부탁드립니다 :D  

[데모 페이지](https://visionary-elf-f8c5fa.netlify.app/)

## 전체적인 구조
- Store하나를 두고 각 컴포넌트에서 Store를 구독하는 형식입니다.
- 컴포넌트에서 action을 dispatch하면 Store의 상태가 변하고, 구독된 컴포넌트에게 알람이 갑니다. 그리고 컴포넌트는 store의 state를 바탕으로 다시 그려집니다.
- 컴포넌트는 HTMLElement를 상속받아 사용했습니다.
- decorator를 사용해 CustomElementRepository에 클래스를 등록하는 과정을 간소화 했습니다.

## Routing
[netlify의 redirect](https://github.com/airman5573/javascript-vendingmachine/blob/step1/netlify.toml)를 사용해 새로고침을 해도 404로 이동되지 않도록 했습니다.

2022-03-29 07:22 UTC, austinpark420 requested changes
안녕하세요 :smile: 

리뷰를 맡은 오스틴입니다.
flux 패턴을 활용하셔서 개발하신 부분이 인상적이었습니다.
관련해서 코멘트 남겨놨으니 확인 부탁드릴게요!

## UX/UI 관련
* 상품 관리 - 상품 현황 리스트 수정을 누르게되면 input 태그크기 때문인지 리스트 높이와 버튼 위치가 변하는데 이 부분 보기/수정 상관없이 리스트와 버튼의 위치가 동일하도록 css를 수정해보시면 좋을 것 같습니다.
* 피그마와 다른 내용이긴 하지만 상품 관리탭에 추가할 상품정보를 입력하는 부분에 placeholder으로 어떤 값을 넣어야하는 설명해주고 있지만 처음 값을 작성할 땐 어떤 항목에 대한 값을 작성하고 있는지 헷갈리는 경우가 있어 라벨이 있으면 어떨까라는 생각을 했습니다.

2022-03-29 07:22 UTC, austinpark420 commented on src/components/navigation.ts
> +          activeTab === Tab.ProductManageTab ? 'active' : ''
3항연산자 말고 &&을 활용하셔도 될것 같습니다.

2022-03-29 07:22 UTC, austinpark420 commented on src/flux/createAction.ts
> +const createAction = (type: string, payload: any): Action => {
👍

2022-03-29 07:22 UTC, austinpark420 commented on src/flux/reducer.ts
> +const reducer = (state: AppState, { type, payload }: Action) => {
👍

2022-03-29 07:22 UTC, austinpark420 commented on src/flux/reducer.ts
> +  return newState;
[switch 문](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch)으로 리페토링 가능하시면 swith 문 활용하시는걸 추천드려요.

2022-03-29 07:22 UTC, austinpark420 commented on src/components/purchase-product-tab.ts
> +    return '<h3 class="text-center">🤖 페이지 건설중...</h3>';
UX/UI를 고려한 부분 좋네요. 👍

2022-03-29 07:22 UTC, austinpark420 commented on src/decorators/decortators.ts
> +export function customElement(name: string) {
개인적으로 궁금해서 그러는데 customElement를 사용하신 이유가 있을까요?

2022-03-29 07:22 UTC, austinpark420 commented on src/components/product-inventory.ts
> +  }
현재 하나의 template으로 기본/수정 화면을 나누고 계시는데 유지보수 측면에서는 두벌로 관리하는 방법도 있습니다!

2022-03-29 07:22 UTC, austinpark420 commented on src/utils.ts
> +export const toInt = (str: string, defaultNum = 0) => {
javascript에서는 Int 타입이 없는데 javascript 타입으로 바꿔주면 어떨까요?

2022-03-29 07:22 UTC, austinpark420 commented on src/utils.ts
> +  return !Number.isNaN(val) ? val : defaultNum;
개인적인 취향이지만 삼항연산자를 쓴다면 아래와 같은 방법으로 작성하는게 가독성이 좀 더 좋아보이는 것 같습니다.
```suggestion
  return Number.isNaN(val) ? defaultNum :  val ;
```

2022-03-29 07:22 UTC, austinpark420 commented on tsconfig.json
> +    "strict": true, // any사용 불허
👍

2022-03-29 07:22 UTC, austinpark420 commented on src/flux/store.ts
> +class Store {
👍

2022-03-29 07:22 UTC, austinpark420 commented on src/components/changes-inventory.ts
> +          <td>${unit.toLocaleString('ko-kr')}원</td>
toLocalString을 필요한 부분에서 사용하고 계신데 유지보수 측면을 생각하시면 통합해서 관리하는 방법을 찾아보시면 좋을 것 같습니다.

2022-03-29 07:22 UTC, austinpark420 commented on src/__test__/validation.test.js
> +    console.log(productList, validateProductName(productName, productList));
제거 못하신거죠?

2022-03-29 07:22 UTC, austinpark420 commented on src/components/navigation.ts
> +  activeLink(target: HTMLElement) {
active 상태관리를 template 안에서 관리 혹은 activeLink함수 중 한곳에서만 관리해주셔도 될 것 같습니다.

2022-03-29 07:22 UTC, austinpark420 commented on src/validation/validators.ts
> +import {
validators.ts 파일이 유독 가독성이 떨어져 보이네요. 🤔

2022-03-29 07:22 UTC, austinpark420 commented on src/validation/validators.ts
> +const isInteger = (str: string) => {
Intger은 javascript에는 없는 타입이네요.

2022-03-29 07:22 UTC, austinpark420 commented on src/components/product-inventory.ts
> +      productList.filter((item) => !(item.name === originalName && item.name === name))
개인적인 취향이지만 드모르간 법칙을 이용해 가독성좋게 바꿔보는건 어떨까요?

2022-03-29 07:22 UTC, austinpark420 commented on src/constants.ts
> +export const MAX_CHARGABLE_MONEY = 100000;
관련있는 변수를 묶어서 관리해도 좋을 것 같습니다.

2022-03-29 07:22 UTC, austinpark420 commented on src/scss/_variables.scss
> +// $color-cancel: $color-cyan-900;
불필요한 주석은 지워주시는게 좋을 것 같습니다.

2022-03-30 16:12 UTC, airman5573 commented on src/utils.ts
> +export const toInt = (str: string, defaultNum = 0) => {
가장 먼저 생각나는건 toNumber정도 입니다.  
toInt는 정수로 변환해 주기 위해 만들었는데, js에서 number는 소수도 포함하는 개념으로 알고 있습니다.  
그래서 저는 정수를 뜻하는 Integer가 더 어울리다고 생각하는데, 리뷰어님의 생각은 어떠신가요?

2022-03-30 16:13 UTC, airman5573 commented on src/__test__/validation.test.js
> +    console.log(productList, validateProductName(productName, productList));
놓쳤습니다. 제거하겠습니다 :D

2022-03-30 16:14 UTC, airman5573 commented on src/validation/validators.ts
> +import {
맞습니다. 다시보니 읽기가 힘드네요. 수정하겠습니다 :D

2022-03-30 16:15 UTC, airman5573 commented on src/validation/validators.ts
> +const isInteger = (str: string) => {
네, 맞습니다. 다만 정수인지를 판단하는 일을 하는 함수라서  
Integer가 직관적이라 더 어울려 보이는데, 리뷰어님의 생각은 어떠신가요?

2022-03-30 16:27 UTC, airman5573 commented on src/components/product-inventory.ts
> +      productList.filter((item) => !(item.name === originalName && item.name === name))
제안 감사합니다 :D  

드모르간 법칙을 적용하면

```
const productList = Store.instance.getState().productList;
const errorList = validateProduct(
    { name, price, quantity },
    productList.filter((item) => item.name !== originalName || item.name !== name)
```
이렇게 되서, 더 잘 읽히는것 같습니다.

다만, 그래도 역시 한번에 이해하기 어려운 코드여서 아래와 같이 바꿔보았습니다.  
```
const productList = Store.instance.getState().productList;
const isEditingSameProduct = (item: ProductItem) => {
  if (originalName === name && item.name === name) return true;
  return false;
};
const errorList = validateProduct(
  { name, price, quantity },
  productList.filter(!isEditingSameProduct)
).filter((result) => result.hasError);
```

이 코드는 어떤가요?

2022-03-30 16:27 UTC, airman5573 commented on src/constants.ts
> +export const MAX_CHARGABLE_MONEY = 100000;
네, 수정하겠습니다 :D

2022-03-30 16:27 UTC, airman5573 commented on src/scss/_variables.scss
> +// $color-cancel: $color-cyan-900;
네, 지우겠습니다 :D

2022-03-30 16:33 UTC, airman5573 commented on src/components/navigation.ts
> +  activeLink(target: HTMLElement) {
꼼꼼한 체크 감사드립니다.  
수정하겠습니다 :D

2022-03-30 16:36 UTC, airman5573 commented on src/utils.ts
> +  return !Number.isNaN(val) ? val : defaultNum;
네, 앞에 !가 붙는것보다 더 읽기가 편하네요.
수정하겠습니다 :D

2022-03-30 16:37 UTC, airman5573 commented on src/components/product-inventory.ts
> +  }
네, 동감입니다. 분리하겠습니다 :D

2022-03-30 16:43 UTC, airman5573 commented on src/decorators/decortators.ts
> +export function customElement(name: string) {
(1) decorator를 적극적으로 활용해 보고 싶었고
(2) `customElements.define('popup-info', PopUpInfo);` 이런식 으로 작성하는것 보다는 약간 더 깔끔해 보였습니다.

2022-03-30 17:16 UTC, airman5573 commented on src/components/navigation.ts
> +          activeTab === Tab.ProductManageTab ? 'active' : ''
`activeTab === Tab.ProductManageTab && 'active'` 를 써보니, false가 class에 들어갑니다.

2022-03-30 17:17 UTC, airman5573 commented on src/flux/reducer.ts
> +  return newState;
네, 그 편이 더 읽기 좋을것 같습니다. 감사합니다 :D

2022-03-31 03:38 UTC, airman5573 commented on src/components/changes-inventory.ts
> +          <td>${unit.toLocaleString('ko-kr')}원</td>
맞습니다,, 좀 긴 코드가 매번 나오니까 약간 지저분해 보였습니다.  
지금으로서는 `Number.prototype.withComma = function...` 이렇게 함수를 추가하는 방법만 생각납니다.  
혹시 `통합해서 관리한다`는게 이런걸 의미하셨던걸까요?

2022-03-31 05:06 UTC, airman5573 commented on src/decorators/decortators.ts
> +export function customElement(name: string) {
아 혹시 customElement자체의 사용 이유에 대한 질문이었다면  
HTMLElement를 상속받은 class안에서 this로 해당 element에 바로 접근이 되서 편했습니다 :D

2022-04-01 09:50 UTC, austinpark420 approved these changes
안녕하세요. 병민님.
아직 리뷰요청을 주시진 않았는데요. 피드백 반영해주신 것으로 확인됩니다.
2단계 진행 및 리뷰 일정 확보를위해 머지하도록 하겠습니다.

step1 구현하시느라 고생많으셨습니다 👍

2022-04-01 09:50 UTC, austinpark420 commented on src/validation/validators.ts
> +const isInteger = (str: string) => {
toInt 함수와 동일한 의견입니다!

2022-04-01 09:50 UTC, austinpark420 commented on src/utils.ts
> +export const toInt = (str: string, defaultNum = 0) => {
디테일하시군요 👍
저는 그냥 보편적으로 숫자라고 생각했는데 병민님 의견 주신 부분이 맞는것 같습니다 🙏

2022-04-01 09:50 UTC, austinpark420 commented on src/decorators/decortators.ts
> +export function customElement(name: string) {
그렇군요. 제가 궁금했던건 `customElement자체의 사용 이유` 였습니다. 
본인의 생각이 명확하시네요 👍

2022-04-01 09:50 UTC, austinpark420 commented on src/components/navigation.ts
> +          activeTab === Tab.ProductManageTab ? 'active' : ''
아고 제가 리엑트 문법에 너무 익숙해져서 간과했던 부분이네요 🙏

2022-04-01 09:50 UTC, austinpark420 commented on src/components/product-inventory.ts
> +      productList.filter((item) => !(item.name === originalName && item.name === name))
👍

2022-04-01 09:50 UTC, austinpark420 commented on src/components/changes-inventory.ts
> +          <td>${unit.toLocaleString('ko-kr')}원</td>
prototype에 직접 추가하는 추천드리지 않습니다.. 어떤 사이드 이펙트가 생길지 모르기때문입니다.
store나 util로 따로 뺄순 있지않나 해서 말씀드렸습니다!

2022-04-01 09:50 UTC, merged