[2단계 - 자판기] 호프(김문희) 미션 제출합니다.
woowacourse/javascript-vendingmachine pull request #61
Opened 2022-04-07 06:09 UTC by moonheekim0118

안녕하세요 헤인티! 오랜만에 뵙습니다 !
헤인티가 주신 피드백 반영하면서 정말 많이 학습할 수 있었어서 좋았어요!

다만..이번에…개인적으로 시간이 없어서 여러 부분을 놓친 점을 알려드립니다.
먼저, e2e 테스트코드를 작성 하지 못했어요.. 😭 😭  지속적으로 추가해놓겠습니다.
그리고, 일단 배포본을 제공해드리지 못한점도 죄송합니다 😭 😭 😭 오늘 내일 내로 꼭 배포본 제공해서 첨부하도록 하겠습니다.
마지막으로, 촉박하게 하다보니까 코드 퀄리티가 조금 안좋아진 것 같아요. 타입스크립트를 사용하면서 타입을 정하지 않은 부분도 많고,  시간 날 때 마다 계속 수정하겠습니다. 그리고 쿼리 셀렉터에 Generic 을 사용해보라는 피드백도, 꼭 반영하겠습니다ㅠㅠ죄송합니다.

먼저 저번에 주신 enum, as const, readonly 에 대해 학습해봤는데요, 아래와 같이 정리 할 수 있었습니다. 아래 정리하면서 타입스크립트에 대해서 많이 학습 할 수 있었어요! 감사드립니다.

###  enum 을 사용하면 안되는 이유

- 결과적으로 말하면 enum을 사용하면 자바스크립트에서 Tree Shaking 이 되지 않습니다.
	- Tree Shaking 이란 사용하지 않는 코드를 삭제하는 기능
	- Tree Shaking 을 통해 export 했지만, 아무데서도 import 하지 않는 모듈을이나 사용하지 않는 코드를 삭제하여 번들 크기를 줄여 페이지가 렌더링 되는 시간을 단축 할 수 있습니다.
	
- enum 은 JavaScript에 존재하지 않고, TypeScript 가 구현한 코드이기 때문에, 즉시실행 함수를 통해 구현됩니다.
- 그런데 번들러는 즉시실행함수를 ‘사용하지 않는 함수’라고 판단 할 수 없기 때문에 Tree-Shaking 이 적용되지 않습니다. 

### readonly 타입이란?
- readonly type 은 인터페이스 속성을 readonly (읽기전용) 으로 지정해줍니다.

```typescript
type Foo {
	readonly bar: number;
	readonly bas: number; 
}

let foo:Foo = { bar:'bar', bas,:'bas' }; // ok

foo.bar = 'bas'; // Error
```

- 위 처럼 readonly 타입으로 지정된 객체 속성은, 초기화는 가능하지만 변경이 불가능 합니다. 

### as const 란?
- as const 를 사용해서 , 타입명으로 타입핑을 하는 대신, ‘const’ assertion을 적용합니다.
- as const 가 적용된 변수는 아래와 같은 특성을 가집니다.
1. 타입이 확장되지 않습니다. 
	- 예를 들어, `const foo = 'bar' as const`  라고 선언 할 경우, 변수 `foo`의 타입은 `string`으로 확장되지 않고, `bar`가 됩니다. 
2. 객체 리터럴에 as const를 지정할 경우, 객체 프로퍼티에 readonly 속성이 지정됩니다.

2022-04-11 03:14 UTC, wmakerjun requested changes
호프 어려운 자판기 2단계 미션 진행하느라 너무너무 고생 많이했어요~ 😆 

피드백 드릴 부분은 코멘트에 남겼는데요 아래 2가지 내용은 자주 코멘트로 언급한것 같아서 한번 더 정리했어요~

특히 네이밍은 저도 어려운 부분이고 늘 고민이 많이 드는데요 ㅎㅎ 지금부터 고민해보고 같은 기능을 다른 사람들은 어떻게 보게 될까를 생각해보면 조금씩 더 잘하게 될 수 있는것 같아요. 참고로 미래의 나도 다른 사람이라고 생각하면 더 의미있는것 같아요 😉 

### 네이밍
메서드 네이밍을 보고 어떤 동작 또는 반환값이 있을지 상상해보면서 봤을 때 추측하기 어려운 부분들이 있었던것 같아요. 먼저 동작 가능한 코드를 작성하면서 충분히 고민할 시간이 부족했던 부분도 있을텐데요. 리팩터링 하면서 한번더 네이밍을 보고 어떤 동작 또는 반환값을 주는지 드러낼 수 있게 만들어 보면 어떨까요~?

### 메세지 상수화
`confirm`, `snackbar`의 경우 상수화한 메시지를 활용하는데, `alert`같은 경우에는 그렇지 않은 경우들이 있는것 같아요. 통일해보면 어떨까요~?

2022-04-11 03:14 UTC, wmakerjun commented on src/css/index.css
> +}
EOL이 등장했어요!

2022-04-11 03:14 UTC, wmakerjun commented on src/css/loginPage.css
> +
앗 이 공백은...!?

2022-04-11 03:14 UTC, wmakerjun commented on src/js/api/index.ts
> +  },
구조가 비슷한 메서드를 한단계 추상화해서 만들어보면 어떨까요~? 재사용가능한 부분들이 보이는것 같아요 🤩

2022-04-11 03:14 UTC, wmakerjun commented on src/css/index.css
> +
사소하지만 이런 공백라인도 동일하게 맞춰가면 좋을 것 같아요 😄

2022-04-11 03:14 UTC, wmakerjun commented on src/js/app.ts
> +    };
👍🏻

2022-04-11 03:14 UTC, wmakerjun commented on src/js/constant/index.ts
> +} as const;
`MAXMUM`, `MINMUM`으로 최대치와 최소값과 같은 경계값들을 다룬다는게 더 잘 드러나는 객체 이름을 고민해보면 어떨까요~?

2022-04-11 03:14 UTC, wmakerjun commented on src/js/domain/authorization.ts
> +  }
`isLoggedIn`이란 메서드는 예상되는 return이 boolean일것 같다는 생각이 드는것 같아요 🤔

2022-04-11 03:14 UTC, wmakerjun commented on src/js/domain/authorization.ts
> +      throw new Error("서버에러");
이 에러 메시지도 상수 관리하는곳에서 함께 다루면 좋을 것 같아요!

2022-04-11 03:14 UTC, wmakerjun commented on src/js/domain/vendingMachine.ts
> +    });
```suggestion
    const product = this.products.find((product) => id === product.getId());
```
이렇게 한 줄로 표현 가능할것 같아요~!

2022-04-11 03:14 UTC, wmakerjun commented on src/js/domain/vendingMachine.ts
> +    count && product.updateCount(count);
`checkDuplicatedName`-`checkValidCount`으로 name, price, count에 대해 유효한지 검증해주고 있는것 같은데 여기에서 name &&, price &&, count &&을 해줘야하는 이유가 있을까요~?

2022-04-11 03:14 UTC, wmakerjun commented on src/js/domain/vendingMachine.ts
> +    }
while문에 조건문이 3가지나 있어서 조금 읽기 어려운 부분이 생기는것 같은데요. 혹시 early return을 이용해서 조건을 좀 더 심플하게 만들어보면 어떨까요~?

2022-04-11 03:14 UTC, wmakerjun commented on src/js/moderator/changesModerator.ts
> +      alert("권한이 없습니다.");
메세지를 상수로 따로 관리해도 좋을것 같아요~!

2022-04-11 03:14 UTC, wmakerjun commented on src/js/moderator/changesModerator.ts
> +      snackbarUI.open(SNACKBAR_TYPE.ALERT, "잔돈이 성공적으로 충전되었습니다!");
메세지를 상수로 따로 관리해도 좋을것 같아요~!

2022-04-11 03:14 UTC, wmakerjun commented on src/js/template/signUp.template.ts
> +  input: () => `
`input`이란 네이밍은 1개의 input만 있을 것 같은데요. 이 input들이 모여 있는 template이라는 의미의 네이밍으로 바꿔보는건 어떨까요~?

2022-04-11 03:14 UTC, wmakerjun commented on src/js/util/validations.ts
> +export const checkNameLength = (name: string) => {
`checkValidPrice`, `checkValidCount`처러 `checkValidName`으로 이름에 대한 유효성 검사를 다뤄주는 객체가 있으면 어떨까요? 이름에 대한 유효성이 추가될때마다 함수가 계속 추가 되는 형태면 관리하기가 조금 어려워질것 같아요 😭 

그리고 모든 validation 함수에 `check-*` 접두어가 붙어있는 형태인데, 보다 적절한 이름은 없을지 고민해볼 필요도 있을것 같아요~! 다른 크루들과 유효성 검증하는 부분을 서로 어떻게 했는지 경험을 공유해보는것도 좋겠죠~? 😉

2022-04-11 03:14 UTC, wmakerjun commented on src/js/util/general.ts
> +        name.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g, "\\$1") +
보통 정규식 같은 경우에는 그 내용을 바로 알기가 어렵기 때문에, 어떤 정규식의 내용인지 따로 변수로 만들어두면 미래의 자신도 읽기가 편해진다는 장점이 있습니다 ㅎㅎ

2022-04-11 03:14 UTC, wmakerjun commented on cypress/integration/authorization.spec.js
> +    cy.get("#name").type(".");
selector, email, password 등 중복해서 사용하는 부분이 많아 보이는데요. 이를 재사용해보면 어떨까요~? 🤔

2022-04-11 03:14 UTC, wmakerjun commented on cypress/integration/authorization.spec.js
> +  });
👍🏻

2022-04-11 03:14 UTC, wmakerjun commented on src/js/domain/vendingMachine.ts
> +    checkValidCount(count);
product의 validation을 한번에 검증해주는 메서드가 따로 있으면, product관련 메서드가 추가될때마다 재사용하기 더 좋을것 같아요~!

2022-04-11 03:14 UTC, wmakerjun commented on src/js/domain/vendingMachine.ts
> +    const coinArray = [500, 100, 50, 10];
coinArray보다 의미를 더 잘 전달할 수 있는 명확한 변수 네이밍이 있을 것 같아요 😉

2022-04-11 03:14 UTC, wmakerjun commented on src/js/domain/vendingMachine.ts
> +  };
getCoins 메서드에서 this.changes를 return해주는게 조금 어색한것 같아요~

2022-04-11 03:14 UTC, wmakerjun commented on src/js/moderator/productModerator.ts
> +      const product = this.vendingMachine.updateProduct(id, name, price, count);
`addProduct`의 경우 객체로 인자를 넣고, `updateProduct`는 4개의 인자를 순서대로 넣는데 혹시 일관되게 구현하지 않는 이유가 있을까요~?

2022-04-11 03:14 UTC, wmakerjun commented on src/js/ui/productPageView.ts
> +  renderDeleteProduct(id: string) {
삭제된 프로덕트를 render한다가 조금 어색한것 같아요!

2022-04-11 03:14 UTC, wmakerjun commented on src/js/ui/snackbarUI.ts
> +    if (this.$container.childElementCount >= 3) {
3은 어떤 의미를 가지는걸까요~? 🤔

2022-04-11 03:14 UTC, wmakerjun commented on cypress/integration/authorization.spec.js
> +const URL = "http://localhost:9000";
[cypress-json](https://docs.cypress.io/guides/references/configuration#cypress-json)을 활용해봐도 좋을것 같아요~!

2022-04-11 03:14 UTC, wmakerjun commented on cypress/integration/authorization.spec.js
> +    cy.get(".submit-button").click();
중복되는 부분을 재사용할 수 있게 리팩터링 한다면 테스트 코드의 가독성도 더 좋아질것 같아요~!

2022-04-11 12:25 UTC, moonheekim0118 commented on src/css/index.css
> +
오..사소한 부분까지 알려주셔서 감사합니다 😄 
[61fa29c](https://github.com/woowacourse/javascript-vendingmachine/pull/61/commits/61fa29c6b16d033c6942408903bb7443483fb342)

2022-04-11 12:25 UTC, moonheekim0118 commented on src/js/app.ts
> +    };
준에게 배운것.... 👍 👍

2022-04-11 13:00 UTC, moonheekim0118 commented on src/js/api/index.ts
> +  },
지금보니 반복되는 부분이 많아서 준 리뷰 대로 조금 수정을 해봤습니다. 특히나 try-catch 에서 response 값을 객체 형태로 넘겨주는 부분은 모두 다 동일하기 때문에, 아예 request 함수에서 처리해주도록 했습니다.

물론 '회원가입' '로그인' '유저정보 수정' 등..의 여러 api 요청 메서드들을 한단계 추상화해서,  외부에서 매개변수만 변경하여 재사용 할만한 메서드 하나를 만들 수 있을 것 같긴하지만 그럴 경우 도메인로직에서 해당 메서드를 사용할 때, 헤더 정보나 url 정보를 불필요하게 알아야한다고 생각해서 말씀해주신 추상화는 하지 않았어요! 이 부분에 대해서 어떻게 생각하시나요~~?

[bc1144d](https://github.com/woowacourse/javascript-vendingmachine/pull/61/commits/bc1144d75503cac358d4316249900d6d92ae5ab0)

2022-04-11 13:04 UTC, moonheekim0118 commented on src/js/constant/index.ts
> +} as const;
감사합니다! 처음에는 당연히 VENDING_MACHINE 도메인과 관련한 상수 숫자들이 들어갈거라고 생각해서 이렇게 지었어요
그런데 구현하다보니,  MIN~MAX 값만 들어가게 되었네요!
이 부분 객체 이름을 `VENDING_MACHINE_BOUNDARY_NUMBER` 로 바꾸어주었습니다 👍 👍 

[7a364de](https://github.com/woowacourse/javascript-vendingmachine/pull/61/commits/7a364debb2827e1680608920e6eb68f5c026ce1c)

2022-04-11 13:09 UTC, moonheekim0118 commented on src/js/domain/authorization.ts
> +  }
동의합니다. 별 생각없이 로그인 여부 체크해주는 메서드여서 저렇게 지었는데, 응답값이 현재 로그인된 유저의 정보네요!
그래서 `isLoggedIn` -> `getLoggedInUser` 로 메서드명 변경해주었어요! 
짚어주셔서 감사합니다. 🙇 

[0b6e49a](https://github.com/woowacourse/javascript-vendingmachine/pull/61/commits/0b6e49a609685f375e9a76f85125ac213690a9c5)

2022-04-11 13:43 UTC, moonheekim0118 commented on src/js/domain/authorization.ts
> +      throw new Error("서버에러");
넵 놓친부분 짚어주셔서 감사합니다!

[6028b23](https://github.com/woowacourse/javascript-vendingmachine/pull/61/commits/6028b23b73827c914512ba60607e94e406f49aba)

2022-04-11 13:46 UTC, moonheekim0118 commented on src/js/domain/vendingMachine.ts
> +    });
감사합니다 : D 반영했어요~!
[da318cd](https://github.com/woowacourse/javascript-vendingmachine/pull/61/commits/da318cd9390ecf41ef4bac14fb60001fba95d5b3)

2022-04-11 14:02 UTC, moonheekim0118 commented on src/js/domain/vendingMachine.ts
> +    count && product.updateCount(count);
앗..이부분 제거했어야하는데 ㅠ_ㅠ놓쳤습니다.
이전에는 사용자가 수정 할 때 만약 name,price,count 를 빈칸으로 놓고 submit 하면, 기존 값으로 덮어씌워서 업데이트 되지 않도록 구현했었거든요! 그 과정에서 누락된 코드였습니다.
짚어주셔서 감사합니다.

[fa96180](https://github.com/woowacourse/javascript-vendingmachine/pull/61/commits/fa96180de96d45e898e5f0851ba423e639c36c8e)

2022-04-11 14:16 UTC, moonheekim0118 commented on src/js/moderator/changesModerator.ts
> +      alert("권한이 없습니다.");
짚어주셔서 감사합니다 ㅎㅎㅎ  반영했어요!

[7e981e7](https://github.com/woowacourse/javascript-vendingmachine/pull/61/commits/7e981e78a425ab3a6a55d589a02d62ec23466e80)

2022-04-11 14:17 UTC, moonheekim0118 commented on src/js/moderator/changesModerator.ts
> +      snackbarUI.open(SNACKBAR_TYPE.ALERT, "잔돈이 성공적으로 충전되었습니다!");
스낵바 관련 alert message 전부 상수화 해서 관리해주었습니다 감사합니다 :D
[7e981e7](https://github.com/woowacourse/javascript-vendingmachine/pull/61/commits/7e981e78a425ab3a6a55d589a02d62ec23466e80)

2022-04-11 16:47 UTC, moonheekim0118 commented on src/js/template/signUp.template.ts
> +  input: () => `
넵 지금 보니까 input 이 하나만 있는것 처럼 보이네요!
`inputCollection` 으로 수정했는데 괜찮을까요~~? 😃  

[08053b2](https://github.com/woowacourse/javascript-vendingmachine/pull/61/commits/08053b28319536c1f787562cde301d378e865009)

2022-04-12 16:55 UTC, moonheekim0118 commented on src/js/util/validations.ts
> +export const checkNameLength = (name: string) => {
네 감사합니다! 지금 보니 Price,Count 는 하나의 함수에서 처리하면서 Name 이나 Changes 는 그러지 않는 점이 매우 통일성도 없네요 😭 
`checkValidName` `checkValidChanges` 로 수정했습니다.
그리고 validation 함수 네이밍 관련해서는 대부분 `isValid-*``checkValid-*` 접두어를 붙여왔는데요, 그 이유가 해당 함수들이 t/f를 반환하기 때문이었어요. 그런데, 제 코드를 다시보니 t/f를 반환하는게 아니라 inValid 할 경우에 Error 를 던져주더라구요..? 그래서 `validate-*` 접두어로 수정해줘봤습니다...!!

[f6d0fa1](https://github.com/woowacourse/javascript-vendingmachine/pull/61/commits/f6d0fa11af3e9145cf24335c36433fb0a6771323)
[7dd00c4](https://github.com/woowacourse/javascript-vendingmachine/pull/61/commits/7dd00c4b7f2e4a5d47841038a2e5922826ff7c59)

2022-04-12 17:12 UTC, moonheekim0118 commented on src/js/util/general.ts
> +        name.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g, "\\$1") +
넵 감사합니다!
일단은 해당 정규 표현식 자체를 아래와 같이 상수 파일에 추가해주었는데요, 준이 말씀하신건 정규식의 모든 조건(?)들을 하나하나 변수에 저장해서 관리해야한다는 것일까요 ?ㅅ? 아니면 이렇게 비밀번호 정규식, 쿠키 정규식을 한번에 관리해도 될까요?

```ts
export const REGEX = {
  PASSWORD: () =>
    new RegExp(
      `^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*])(?=.{${AUTHORIZATION_BOUNDARY_NUMBER.MINIMUM_PASSWORD_LENGTH},})`
    ),
  COOKIE: (name) =>
    new RegExp(
      // eslint-disable-next-line no-useless-escape
      `(?:^|; )${name.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g, "\\$1")}"=([^;]*)`
    ),
};
```

[ef46977](https://github.com/woowacourse/javascript-vendingmachine/pull/61/commits/ef46977e70f7a22221a844225d6b6996d669eeab)

2022-04-12 17:13 UTC, moonheekim0118 commented on cypress/integration/authorization.spec.js
> +  });
감사합니다 :)

2022-04-12 17:20 UTC, moonheekim0118 commented on src/js/domain/vendingMachine.ts
> +    checkValidCount(count);
넵 :) 동의합니다!
그래서 필요한 매개변수를 객체로 받고, 모든 validation 함수를 실행하는 `validateProduct` 함수를 작성해보았습니다 :) 의견감사드려요 👍  
```ts
export const validateProduct = ({ products, name, price, count, id = "" }) => {
  validateProductName(products, name, id);
  validateProductPrice(price);
  validateProductCount(count);
};
```

[e28e283](https://github.com/moonheekim0118/javascript-vendingmachine/commit/e28e2839b4cef8ccd800c0635bf5b28806b708d3)

2022-04-12 17:23 UTC, moonheekim0118 commented on src/js/domain/vendingMachine.ts
> +    const coinArray = [500, 100, 50, 10];
동전의 종류니까 coinTypes 로 해봤는데 괜찮을까요 ?ㅅ?

[dd3760e](https://github.com/moonheekim0118/javascript-vendingmachine/commit/dd3760ed73ae2985e030c955d8b573b5bbc6d716)

2022-04-12 17:35 UTC, moonheekim0118 commented on src/js/domain/vendingMachine.ts
> +  };
그렇네요! 이 부분 변경해서 getCoins -> getChanges 로 수정했습니다 :D 
changes 가 단순히 coin 종류여서 getCoins라구 했는데, 이렇게 하다보니 리턴되는 멤버변수 명과 메서드명이 일치하지 않게 되어버렸네요 😭  다음부터는 신경쓰겠습니다 👍 

[39101df](https://github.com/moonheekim0118/javascript-vendingmachine/commit/39101df131c18fb9d6995c121e3f0d22e533e82e)

2022-04-12 17:40 UTC, moonheekim0118 commented on src/js/moderator/productModerator.ts
> +      const product = this.vendingMachine.updateProduct(id, name, price, count);
급하게 하느라 통일성을 지키지 못했네요 😭 😭  이 부분 수정해서 둘다 객체로 인자를 받도록 했습니다. 이렇게 사소한 부분까지 짚어주셔서 감사해요!
[9716133](https://github.com/moonheekim0118/javascript-vendingmachine/commit/9716133e44420c21cb64ef49b7c929355c1f21df)

2022-04-12 17:44 UTC, moonheekim0118 commented on src/js/ui/productPageView.ts
> +  renderDeleteProduct(id: string) {
단순히, 뷰에 보여주는 부분을 변경한다고해서 `render-*` 접두사를 써야한다고 생각해서 저런 요상한 네이밍이 나왔네요 ㅋㅋㅋㅠㅠ
근데 생각해보니 해당 함수가 **렌더링된 아이템을 삭제해주는 작업**을 해주기 때문에 `deleteRenderedProduct` 라고 수정해주었습니다 :D 
감사합니다.

[56293e9](https://github.com/moonheekim0118/javascript-vendingmachine/commit/56293e9bd7c71e9b0527cbb48ac253d1e9f0e8eb)

2022-04-12 17:47 UTC, moonheekim0118 commented on src/js/ui/snackbarUI.ts
> +    if (this.$container.childElementCount >= 3) {
스낵바가 여러개가 동시에 화면에 보여져야할 경우 최대 3개까지 보여지게 해놨기때문에 들어간 숫자인데 이렇게 놓으면....정말 코드를 읽는 입장에서는 뭐지??! 싶겠네요 ... 상수로 분리해주겠습니다 :D 감사합니다.

[93b4899](https://github.com/moonheekim0118/javascript-vendingmachine/commit/93b48999f11ff22b8c2cfbadb260c94a2112d375)

2022-04-12 18:00 UTC, moonheekim0118 commented on cypress/integration/authorization.spec.js
> +const URL = "http://localhost:9000";
감사합니다~ 훨씬 간결해졌네요 👍 👍 👍 

[f272fd4](https://github.com/moonheekim0118/javascript-vendingmachine/commit/f272fd4e76ceb966414e53266d2bb7cf57a69b27)

2022-04-12 18:22 UTC, moonheekim0118 commented on cypress/integration/authorization.spec.js
> +    cy.get(".submit-button").click();
이 부분 cypress commands 사용해서 해결했습니다 :)
계속 반복해서 사용되는 signUp 과 login 을 커맨드로 빼놓으니까 너무 간결하네요
감사합니당 👍 
[b99dd1f](https://github.com/moonheekim0118/javascript-vendingmachine/commit/b99dd1f5b014951ab3f5f4306b55e20a4a7ae6fb)

2022-04-12 18:37 UTC, moonheekim0118 commented on cypress/integration/authorization.spec.js
> +    cy.get("#name").type(".");
넵. 계속 사용되는 selector 들과 email, password 등을 util 로 분리해주었습니다 👍 👍 
훠어얼씬 깔끔해졌네요 👍 👍  감사합니다.

[37ca5d1](https://github.com/moonheekim0118/javascript-vendingmachine/commit/37ca5d154ad8ab83fc73ab8a8d8702af49f8789b)

2022-04-12 18:48 UTC, moonheekim0118 commented
![](https://dn-img-page.kakao.com/download/resource?kid=pMlAn/hyLjfWT4lx/w7Ivc3QKPix4bzBgJ0Xvb0)

안녕하세요 준 😄  정말 좋은 리뷰 감사드립니다! 
말씀해주신 대로, 상수분리와 네이밍 관련해서 피드백 반영 완료했습니다 :D 
코드를 다시 보다보니, 저번주에 급해서 놓쳤던 부분이 한 두군데가 아니네요 😭...코드리뷰 하시느라 정말 고생하셨습니다..큽..
cypress 에서도 Commands 를 사용해서 계속해서 반복되는 로직 (로그인,회원가입)을 줄였고, constants 를 정의해주었습니다 !

그럼에도 불구하고 아직 네이밍관련해서는 '더 좋은 네이밍' 에 대한 의문이 끊이질 않네요 😭 .. 준이 주신 피드백들 참고해서 앞으로 더 좋고 명확한 네이밍을 하도록 노력해보도록 하겠습니다 :D  

혹시나 더 수정할 부분이 있거나, 궁금하신 점이 있다면 알려주시면 감사하겠습니다 🙇 🙇 
다시 한번 좋은 리뷰 정말 감사드려요 👍 👍 👍 👍

2022-04-15 05:19 UTC, wmakerjun commented on src/js/api/index.ts
> +  },
한단계 추상화했을 뿐만 아니라, 객체의 책임과 관련된 부분까지 고민해서 작업한 점이 너무 인상적이에요 👍🏻 
그런데 `const data = await response.json();`이 부분에서 `response.json()`이 실패한 경우에 에러 처리는 어떻게 해줘야할지도 고민되는 것 같아요. fetch API 사용하는 로직은 앞으로도 계속 사용하는 부분이니 이 미션이 아니어도, 다음 미션에서 반영해보면 좋을 것 같아요!

2022-04-15 05:25 UTC, wmakerjun commented on src/js/constant/index.ts
> +} as const;
훨씬 더 명확한 네이밍이 된것 같아요!

2022-04-15 05:26 UTC, wmakerjun commented on src/js/domain/authorization.ts
> +  }
저도 흔히 놓치는 것인데 가끔은 메서드를 모두 folding해놓고 어떤 데이터값을 return할지 추측해보면 더 좋은 네이밍을 고민하는데 도움이 되더라구요!

2022-04-15 05:27 UTC, wmakerjun commented on src/js/util/validations.ts
> +export const checkNameLength = (name: string) => {
우와... 호프는 정말 응용력이 뛰어난것 같아요. 한 가지에 대해 피드백 드렸는데 다른 관련된 부분까지 같이 고려하였군요 👍🏻

2022-04-15 05:38 UTC, wmakerjun commented on src/js/util/general.ts
> +        name.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g, "\\$1") +
제가 말한 의미는 정규식만 보고서는 어떤 의미를 가지고 있는지 파악하기 어렵기 때문에, 변수 또는 상수로 표현하면 더 좋을것 같다는 의미였어요~. 그 조건들을 하나하나의 변수에 담을지, 의미있는 정규식 표현 단위로 객체로 묶을지는 호프에게 혹은 팀에게 달린것 같아요 😄 
정규식을 사용하는 곳이 많아진다면 [링크](https://github.com/francisrstokes/super-expressive#Installation-and-Usage)에서 볼 수 있는 예시도 가능해질 것 같아요~

정규식이 보기 쉬운 형태가 아니기 때문에... 그 의미를 적어두지 않는다면 굉장히 헷갈리더라구요 하하;;

의미를 담는 과정이라고 생각해주시면 될 것 같아요 ㅎㅎ

2022-04-15 05:39 UTC, wmakerjun approved these changes

2022-04-15 05:42 UTC, wmakerjun commented
호프~ 정말 빠르게 피드백 반영해주고, 고민한 과정까지 상세하게 남겨줘서 소통하는 과정이 너무 큰 즐거움이었어요! 
네이밍은 코치들 역시 계속해서 고민이 많이 되는 과정인데여 😭 
읽기 좋은 네이밍은 혼자서 고민하기 보다는 주변 사람들과 피드백 주고 받을 때 확실히 더 명확한 아이디어가 많이 떠오르더라구요. 고민되는 네이밍이 있다면 다른 크루들과 의견 주고 받으면서 '어떤 과정을 통해 좋은 네이밍이 나올 수 있을까?'에 대한 호프만의 방법을 찾아나가면 너무 멋질것 같아요.

우테코 수료할 때 쯤엔 "네이밍은 여전히 어렵지만, 이렇게 접근하면 더 나은 네이밍을 만들 수 있는것 같아!"라는 호프만의 철학이 있으면 너무 눈부실것 같습니다 🤩 

너무너무 고생했구요 레벨2에서 만날게요! 😆

2022-04-15 05:43 UTC, merged