[2단계 - 자판기] 태태(김태윤) 미션 제출합니다.
woowacourse/javascript-vendingmachine pull request #63
Opened 2022-04-07 06:47 UTC by nan-noo

안녕하세요~~

[데모 페이지](https://nan-noo.github.io/javascript-vendingmachine/)
> 서버를 heroku에 배포했는데, 무료 버전은 30분마다 서버가 꺼져서 첫 요청하고 응답 받는 데에 오래 걸립니다!
> 로컬 실행 방법은 리드미에 적혀 있습니다.

## 구현
* 구조
   * app.js에서 hash가 바뀔때마다 라우팅
   * 로그인 했을 때, 탭이 있는 페이지(관리자 페이지)
      * 상품 관리 탭
      * 잔돈 충전 탭
      * 상품 구매 탭
   * 로그인 페이지
   * 회원가입 페이지
* 로그인 여부에 따라 특정 경로로 접근 시 리다이렉트(hash로 흉내)
* 새로고침 하지 않으면 기존에 입력한 상품 목록 및 잔돈 모두 유지
* alert 대신 snackbar 사용
* accessToken은 쿠키에, username은 localStorage에 저장. 둘 다 쿠키에 저장하지 않은 이유는, 쿠키에 너무 많은 데이터를 담으면 네트워크 과부하가 올 수 있다고 알아서 꼭 필요한 데이터만 쿠키에 담았습니다. 

## 아쉬운 점
* 이번에 기능 구현과 버그 해결에 신경쓰느라 구조가 맘에 들지 않습니다.. ㅠㅠ 상품 구매 탭 뷰에서 상품 관리와 잔돈 충전이 갖고 있는 itemList와 coinCollection을 사용해야 해서 일단 멤버로 넣었는데, 나중에 데이터만 들고 있는 객체(모델?)를 따로 만들어서 관리할까 생각 중입니다. 더 좋은 방법이 있을까요?
* E2E 테스트 코드는 일단 주요 기능(성공하는 경우)만 작성했습니다. 
* 스낵바를 requestAnimationFrame으로 구현했는데, 중복해서(연속해서) 스낵바를 호출하는 것을 아직 방지하지 못했습니다. -> 함수 반환값을 이용해서 debounce 로 해결할 수 있을 것 같습니다. 
* 서버에서 에러 메세지를 영어로 보내고 있어서 로그인, 회원가입 오류일 때 스낵바에 영어 메세지가 뜹니다..!(Email Already Exists 등등)
* 템플릿을 사용하여 렌더링했는데, 중복되는 부분이 많은데 분리하지 못했습니다.

이번에도 피드백 많이 남겨주세요..! 감사합니다.

2022-04-07 14:48 UTC, austinpark420 requested changes
안녕하세요. 태태 😄 
네이밍이 일관성이 있어 코드를 볼 때 쉽게 역할을 유추하면서 볼 수 있어서 좋았습니다.
시간이되시면 예외처리에 대한 테스트코드를 추가해보셔도 좋을 것 같습니다.
기능 구현하시느라 고생 많으셨습니다 :thumbsup:

## 질문에대한 생각
이번에 기능 구현과 버그 해결에 신경쓰느라 구조가 맘에 들지 않습니다.. ㅠㅠ 상품 구매 탭 뷰에서 상품 관리와 잔돈 충전이 갖고 있는 itemList와 coinCollection을 사용해야 해서 일단 멤버로 넣었는데, 나중에 데이터만 들고 있는 객체(모델?)를 따로 만들어서 관리할까 생각 중입니다. 더 좋은 방법이 있을까요?
* 지금 프로젝트에서는 크게 문제가 없다고 생각하는데요. 말씀주신 것처럼 상품과, 잔돈 등을 스토어로 만들어서 관리하는 구조로 잡아보시는게 좋을 것 같습니다.

## 수정해야할 점
* 상품구매 탭에 잔돈반환시 아무런 금액을 반환하지 않아도 일부만 반환되었습니다. 자판기 관리자에게 문의해주세요. 라는 스낵바 문구가 뜨고 있습니다. 아무런 금액을 반환하지않는 것과 일부만 반환되는 케이스를 나눠야할 것 같습니다.

2022-04-07 14:48 UTC, austinpark420 commented on cypress/integration/itemManageTab.spec.js
> +    cy.get(SELECTOR.TABLE_ROW).eq(1).should('have.attr', 'data-item-name', itemName);
상수로 변경하셨네요 👍

2022-04-07 14:48 UTC, austinpark420 commented on index.html
> +    <main id="app"></main>
index.html을 깔끔하게 리팩토링 하셨네요 👍

2022-04-07 14:48 UTC, austinpark420 commented on index.html
>  </html>
인덴트가 안맞네요. html 파일 관련된 프리티어 설정이 안되어있을까요?
```suggestion
  </body>

</html>
```

2022-04-07 14:48 UTC, austinpark420 commented on src/__test__/itemPurchase.test.ts
> +  });
꼭필요한 테스트 일까요? 위에 에러가 발생하는 테스트를 했다면 필요한 테스트일까 생각이 들어서 말씀드렸습니다.

2022-04-07 14:48 UTC, austinpark420 commented on src/ts/app.js
> +      case '':
잘못 들어간 부분인거죠?

2022-04-07 14:48 UTC, austinpark420 commented on src/ts/template/index.js
> +export const generateItemPurchaseContentTemplate = (moneyAmount, itemList, change) => `
매개 변수가 3개 이상일 경우, 객체로 받는 것이 실수 방지할 수 있습니다.

2022-04-07 14:48 UTC, austinpark420 commented on src/ts/utils/fetchServer.js
> +const postServer = (baseUrl) => (path) => async (bodyData) => {
👍

2022-04-07 14:48 UTC, austinpark420 commented on src/ts/utils/fetchServer.js
> +  return [response.ok, await response.json()];
배열로 반환할 때, 순서를 보장해서 받아야하기 때문에 확장성을 고려하면 이 부분도 객체 형태로 return하는 것을 추천드려요.

2022-04-07 14:48 UTC, austinpark420 commented on src/ts/utils/index.js
> +      requestAnimationFrame(snackbarAnimation);
requestAnimationFrame 👍

2022-04-07 14:48 UTC, austinpark420 commented on src/ts/app.js
> +import LoginUserPage from './view/LoginUserPage';
view에 index.js같은 파일을 만들어서 중복되는 import를 줄여봐도 좋을것 같습니다.

2022-04-07 14:48 UTC, austinpark420 commented on src/ts/app.js
> +        accessToken
사소하지만 accessToken를 삼항연자사로 사용할 때, 아래와 같이 2가지 케이스가 있는 것 같은데 하나로 통일하는게 좋을 것 같습니다.
* accessToken
* !accessToken

2022-04-07 14:48 UTC, austinpark420 commented on src/ts/constant/errorMessage.js
>    EXCEED_TOTAL_AMOUNT_RANGE: '보유할 수 있는 최소 금액은 0원, 최대 금액은 100,000원입니다.',
최소금액, 최대금액 등 요구사항이 변했을 때, 에러 메세지를 일일히 수정해야하는 구조로 되어 있네요.
이런 상황이라면 나중에 휴먼에러가 날 가능성이 높아보입니다.

2022-04-07 14:48 UTC, austinpark420 commented on src/ts/vendingMachine/authLogic.ts
> +const isBlankInput = (email: string, name: string, password: string, confirmPassword: string) => {
파일 전체적으로 봤을 때, prettier가 제대로 동작하지 않는 것 같습니다.
띄어쓰기, `;`의 유무가 일관성이 없네요. 이 부분 확인 부탁드릴게요. (해당 파일과 ItemManage의 파일을 비교해보시면 차이가 바로 보이실 것 같습니다.)

2022-04-07 14:48 UTC, austinpark420 commented on src/ts/view/AdminPage.js
> +        break;
2가지 케이스를 처리하기위해서는 case보다는 다른 방법을 추천드려요.

2022-04-09 04:14 UTC, nan-noo commented on cypress/integration/itemManageTab.spec.js
> +    cy.get(SELECTOR.TABLE_ROW).eq(1).should('have.attr', 'data-item-name', itemName);
너무 많이 반복되더라구요..!ㅎㅎ

2022-04-09 04:20 UTC, nan-noo commented on index.html
>  </html>
설정한 줄 알았는데, 기본 포매터가 HTML 언어 기능으로 되어 있었네요..ㅎㅎ 수정했습니다!

2022-04-09 04:21 UTC, nan-noo commented on src/ts/app.js
> +      case '':
루트 경로로 접근했을 때도 상품 구매 탭이 렌더링 되도록 구현해서 저 케이스를 추가했습니다

2022-04-09 04:22 UTC, nan-noo commented on src/ts/utils/fetchServer.js
> +const postServer = (baseUrl) => (path) => async (bodyData) => {
책에서 읽어서 한 번 써보려고 했습니다ㅎㅎ

2022-04-09 05:20 UTC, nan-noo commented on src/ts/vendingMachine/authLogic.ts
> +const isBlankInput = (email: string, name: string, password: string, confirmPassword: string) => {
eslint에 문제가 있었네요.. 버전 달라지면서 extends를 수정해야 했는데, 예전 버전을 썼습니다ㅠㅠ
https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21

2022-04-09 06:18 UTC, nan-noo commented on src/ts/constant/errorMessage.js
>    EXCEED_TOTAL_AMOUNT_RANGE: '보유할 수 있는 최소 금액은 0원, 최대 금액은 100,000원입니다.',
아 이거 수정하려고 했는데 깜박했네요 :ㅇ
수정했습니다!!

2022-04-09 06:54 UTC, nan-noo commented on src/ts/view/AdminPage.js
> +        break;
if문으로 수정했습니다!

2022-04-09 13:45 UTC, nan-noo commented on src/__test__/itemPurchase.test.ts
> +  });
만약 코드를 잘못 작성했으면, 올바른 값을 입력했을 때 에러가 발생할 수도 있지 않을까 생각해서 테스트 케이스를 넣은 건데, 어떻게 생각하시나요??

2022-04-11 07:27 UTC, austinpark420 commented on src/__test__/itemPurchase.test.ts
> +  });
그런 의도셨군요! 휴먼에러를 방지하기위한 방어코드네요.👍

2022-04-12 00:54 UTC, austinpark420 approved these changes
안녕하세요 태태!
피드백 반영해주신 부분 확인했습니다. 미션 수행하시느라 고생많으셨습니다. 👍 
이번 미션은 여기서 머지를 해도 될 것 같습니다.
남은 기간 방학 잘보내세요 😄

2022-04-12 00:54 UTC, merged