[2단계 - 자판기] 마르코(장원석) 미션 제출합니다.
woowacourse/javascript-vendingmachine pull request #68
Opened 2022-04-07 08:01 UTC by wonsss

안녕하세요. 리뷰어님. 한 주간 잘 지내셨나요? 완연한 봄이 다가온 것 같아 기분이 정말 좋아요.
저는 한 주간 자판기와 열심히 씨름했는데요. 아직 제 코드에 미숙한 점도 많고, 리팩토링할 부분도 너무 많지만 일단 피드백을 받는 게 우선일 것 같아 PR을 제출드립니다. 데모 페이지 링크는 아래와 같습니다.
### [자판기 데모페이지](https://wonsss.github.io/javascript-vendingmachine/)

## 노력한 점
- `json-server` 웹서버를 heroku에 배포하여 사용했습니다. 따라서 데모페이지에서 로그인, 회원가입 등 이용하실 수 있습니다.
- 로그인, 회원가입 등 인증/인가 관리는 Cookie를 이용하였습니다. 로그인 후 1시간이 지나면 유효기간이 만료되도록 설정했습니다.
- step2 이후로는 처음으로 웹컴포넌트를 활용해보았습니다. Toast알림모달창 및 로그인창, 회원가입창, 회원정보수정창 등을 웹컴포넌트로 만들어보았습니다. 하지만 아쉽게도 step1에서 만들었던 기존 view들은 시간 관계상 수정하지 못했습니다.
- 로그인, 회원가입, 회원정보 수정 등의 화면은 새 url이 아니라 기존 화면 위에 모달창을 띄우는 방식으로 만들어봤습니다. 사용성에 이 방법이 더 좋을 것 같아 시도했는데, 다시 생각해보니 아쉬운 점도 남네요(이 부분은 아래에서 더 말씀드릴게요)
- 회원가입 및 로그인이 필요한 E2E 테스트에서는 고정된 상수값(아이디, 비밀번호)을 입력하면 일회용 테스트라는 한계가 있었습니다. 이를 해결하기 위해, 테스트할 때마다 랜덤으로 생성한 아이디로 새로 회원가입을 하게 만들었습니다.

## 고민되는 점
- 로그인하지 않은 사용자가 로그인전용 페이지에 접근하려고 할 경우, 이를 제한하는 로직에 문제가 있음을 이제 깨달았습니다.. 현재는  step1에서만든 것을 그대로 이어 받아, 세 개의 탭 section 태그 classList에 hide를 주고 있습니다. 그런데 이러면 사용자가 개발자도구에서 직접 classList의 hide를 삭제하면 접근제한이 의미가 없어지네요...ㅎㅎ 그런데 이렇게 했던 이유는 SSR 처럼 하고 싶어서였는데요. 이제 생각해보니, SSR을 하더라도 접근하기 위해 인증이 필요한 부분은 html에 미리 넣어두면 안 될 것 같다는 생각이 드네요. 따라서, 이 문제를 해결하기 위해, 접근제한 페이지는 미리 html에 넣어두지 않고 로그인 여부에 따라 필요한 부분만 insertAdjacentHTML을 해야할 것 같습니다. 리뷰어님께서는 이에 대해 어떻게 생각하시나요? 이 부분은 피드백 받는 과정에서 리팩토링하도록 하겠습니다.
- 웹컴포넌트(shadowDom)에서 발생한 이벤트를 외부로 전달하는 방법으로 커스텀 이벤트를 사용했습니다. 다른 방법이 잘 떠오르지 않아서, 커스텀 이벤트를 썼는데, 어떻게 생각하시나요? ㅠㅠ웹컴포넌트를 사용할 때는 옵저버 패턴을 사용하는 게 더 좋을 것 같다는 생각이 들었어요.

2022-04-09 06:27 UTC, hyoungnam requested changes
안녕하세요 마르코님!! 제가 로컬로 프로젝트를 구동하였을때 API 요청을 날릴수 없어 리뷰를 제대로 진행할 수 없을듯 합니다. 보통 코드를 건드려보고 수정도 해보는편이라..ㅠ 이부분 한번 확인해주세요~!

2022-04-09 12:05 UTC, hyoungnam requested changes
안녕하세요 마르코님~! 구조나 코드 가독성있게 잘 작성해주시고 역할 잘 나누어신것 같습니다. 저번 미션에서 수정요청했던 부분들 반영도 잘해주셨고 웹컴포넌트가 섞여있는게 인상적이네요. 
고민되는점 답변드려요

> 로그인하지 않은 사용자가 로그인전용 페이지에 접근하려고 할 경우, 이를 제한하는 로직에 문제가 있음을 이제 깨달았습니다.. 현재는 step1에서만든 것을 그대로 이어 받아, 세 개의 탭 section 태그 classList에 hide를 주고 있습니다. 그런데 이러면 사용자가 개발자도구에서 직접 classList의 hide를 삭제하면 접근제한이 의미가 없어지네요...ㅎㅎ 그런데 이렇게 했던 이유는 SSR 처럼 하고 싶어서였는데요. 이제 생각해보니, SSR을 하더라도 �접근하기 위해 인증이 필요한 부분은 html에 미리 넣어두면 안 될 것 같다는 생각이 드네요. 따라서, 이 문제를 해결하기 위해, 접근제한 페이지는 미리 html에 넣어두지 않고 로그인 여부에 따라 필요한 부분만 insertAdjacentHTML을 해야할 것 같습니다. 리뷰어님께서는 이에 대해 어떻게 생각하시나요? 이 부분은 피드백 받는 과정에서 리팩토링하도록 하겠습니다.

마르코님 생각하신것처럼 미리 hide로 가리는건 문제가 있죠. 필요한 부분만 insertAdjacent하여 렌더링하는것이 좋을것 같습니다.

> 웹컴포넌트(shadowDom)에서 발생한 이벤트를 외부로 전달하는 방법으로 커스텀 이벤트를 사용했습니다. 다른 방법이 잘 떠오르지 않아서, 커스텀 이벤트를 썼습니다. 웹컴포넌트를 사용할 때는 옵저버 패턴을 사용하는 게 더 좋을 것 같다는 생각이 들었어요. 어떻게 생각하시나요?

웹 컴포넌트를 잘 사용하지 않아서 더 좋을지 잘 모르겠습니다

> 로그인, 회원가입, 회원정보수정은 라우터를 쓰지 않고 모달을 display 변경만 해주어서, url로 접근할 수가 없습니다. 사용성을 좋게 하기 위해 모달을 쓴 건데, 라우팅되어 url로 접근하도록 만드는 게 더 좋을 것 같다는 생각도 드네요.

로그인과 회원가입은 url로 접근하는게 좋을것 같습니다. 회원가입과 로그인 기능은 서비스 진입의 관문이죠. '마케팅 퍼널'이란 단어를 검색하면 깔떄기 모양이 나오는데 저희가 해야될 작업은 이 깔때기의 시작부터 끝까지 소비자를 매끄럽게 끌어들이고 가치를 창출하는 것이라고 생각합니다. 시작이 매끄럽지 않다면 끝으로 가지도 못하죠

간단한 코멘트 몇가지 남겼으니 확인해주세요~!

2022-04-09 12:05 UTC, hyoungnam commented on src/ts/components/renderer.ts
> +};
router에 위치하고 있어도 괜찮을것 같은데 따로 뺀 이유가 있나요??

2022-04-09 12:05 UTC, hyoungnam commented on src/ts/domains/Product.ts
>  interface ProductInterface extends ProductType {
파일에 변화에 표기가 안되서 이 라인에 코멘트 남겨요
```
 public set name(name) {
    this._name = name;
  }

  public set price(price) {
    this._price = price;
  }

  public set quantity(quantity) {
    this._quantity = quantity;
  }
}
```
 이 setter 함수들은 사용하는곳이 없는곳 같고 없다면 삭제하는게 맞습니다. 불필요하게 setter를 만들고 노출할 필요는 없죠.

2022-04-09 12:05 UTC, hyoungnam commented on src/ts/views/ProductManageView.ts
> +export default class ProductManageView {
이 코멘트도 지난번에 놓쳐서 여기에다가 달아요
handleEdit 부분
```
 private handleEdit = (target: HTMLButtonElement) => {
    const { name, price, quantity } = this.vendingMachine.getProduct(target.dataset.name);
    const editTemplate = this.getEditTemplate({ name, price, quantity });
    const targetEdit = $(`tr[data-name='${name}']`);
    targetEdit.replaceChildren();
    targetEdit.insertAdjacentHTML('beforeend', editTemplate);

    $('.edit-confirm-button').addEventListener('click', () => this.handleConfirmEdit(name));
  };

  private getEditTemplate = ({ name, price, quantity }: ProductType) => {
    return `
    <tr class="product-row" dataset-name=${name} >
      <td class="product-row-name">
        <input class="edit-input" id="edit-name-input" type="text" size="10" minlength="1" maxlength="10" value="${name}">
      </td>
     .......
    <tr class="product-row">
    `;
  };
```
이렇게 수정할수 있지 않을까 생각되네요

명령형과 선언형 조작이 섞여있으면 가독성이 떨어져서 한쪽으로 밀고 가는게 더 읽기 편하다고 봅니다
[그래서 DECLARATIVE가 뭔데?](https://youtu.be/r7M9B_dEbCI?t=207)

2022-04-09 12:05 UTC, hyoungnam commented on src/ts/components/Login.ts
> +loginTemplate.innerHTML = `
css 파일을 사용하지 않고 내부 스타일 시트를 넣어준 이유가 무엇인가요???

2022-04-09 12:05 UTC, hyoungnam commented on src/ts/components/Login.ts
> +  closeModalDimmer = (event) => {
```
closeModalDimmer = (event) => {
    if (event.target === this.dimmer) {
      this.closeModal();
    }
  };
```
매번 셀렉팅하는것보다 멤버 변수로 저장해도 될듯하며 boolean 리턴이 필요해보이지는 않는것 같네요.
개인적으로 삼항연산자를 통해 반환값을 받는게 명시적이고 함수를 호출하는건 가독성이 떨어지지 않나 생각합니다

2022-04-09 12:05 UTC, hyoungnam commented on src/ts/views/PurchaseView.ts
> +  private renderRefundTable = () => {};
😱😱😱 주석은 웹팩 덕분에 번들링 과정에서 없어지지만 이 친구는 살아남을테니.. 살아남지 않도록 제거합시다

2022-04-09 12:05 UTC, hyoungnam commented on cypress/integration/purchase.spec.js
> +  it('사용자는 규칙에 적합한 금액을 투입할 수 있다', () => {
적합한 금액은 얼마인가요😶

2022-04-09 12:05 UTC, hyoungnam commented on cypress/integration/purchase.spec.js
> +      _name: '사이다',
언더바 사용기준이 어떻게 되나요??

2022-04-09 12:05 UTC, hyoungnam commented on cypress/integration/purchase.spec.js
> +    cy.get('#purchase-tab-coin-10').last().should('have.text', '4');
[alias](https://docs.cypress.io/guides/core-concepts/variables-and-aliases#Sharing-Context)를 활용하여도 좋을것 같네요:)

2022-04-10 13:54 UTC, wonsss commented on src/ts/domains/Product.ts
>  interface ProductInterface extends ProductType {
넵! 사용하는 곳이 없는 setter였네요. 불필요한 setter를 삭제하였습니다.
[♻️ 불필요한 setter 삭제](https://github.com/woowacourse/javascript-vendingmachine/pull/68/commits/7fce933421079df741dc4ea4f35eb2e31184b254)

2022-04-10 14:41 UTC, wonsss commented on src/ts/views/ProductManageView.ts
> +export default class ProductManageView {
예시로 들어주신 코드처럼 handleEdit 부분은 리팩토링하였습니다!
그리고 첨부해주신 영상을 읽고 정리해보았습니다. 이와 관련하여 추가 리팩토링할 부분도 확인해보겠습니다.

- 선언적(Declartive)
	-  	컴포넌트는 선언적이다. 컴포넌트는 개발자로 하여금 어떻게(How) UI를 그려야 할지에 대한 고민 없이 주어진 상태에 기반해서 어떤(What) UI가 생겨야 하는지 적기만 하면 되도록 도와준다.

```js
// Impertaive Code
// what
const greeting = `Hello, Marco!`;

// how
const $p = document.createElement("p");
$p.innerHTML = greeting;

const $app = document.getElementById("app");
$app.appendChild($p);
```
- 위 코드에서 How와 What을 분리하면 아래와 같은 코드가 된다. 코드가 더 직관적으로 변하였다.
```js
// Declartive Code
// how
function p(text) {
	const $p = document.createElement("p");
	$p.innerHTML = text;
	return $p;
}
function render(element) {
	const $app = document.getElementById("app");
	$app.appendChild(element);
}

// what
const greeting = `Hello, Marco!`;
render(p(greeting));
```
<동적으로 내용 변경되는 코드 예시>
- How랑 What분리하여 delcartive하게 만들기 - "상태를 뷰에 반영한다"
- 	`How`를 최소화하고, `What`에 집중하기
	-  `How` - 어떻게 데이터를 바꿀까? 언제 데이터를 바꿀까?
	-  `What` -  무슨 데이터를 바꿀까? 어디에 값을 보여줄까?
버튼을 누를 때마다 카운트가 하나씩 증가하는 코드
```js
//  imperative code
// What
let count = 2020;
const $button = document.getElementById("button");

// How
$button.addEventListener("click", () => {
	// What
	const $count = document.getElementById("count");
	count += 1;
	$count.innerHTML = count;
});
```
위 코드는 How랑 What이 섞여있다. render()의 인자를 함수 형태로 받고 상태 개념을 도입하여 How를 분리하자.
```js
function render(initialState, createElement) {
	function renderToApp(element) {
		const $app = document.getElementById("app");
		$app.replaceChildren();
		$app.appendChild(element);
	}
	function setState(state) {
		renderToApp(createElement(state, setState));
	}
	
	setState(initialState);
}
``` 
```js
import { div, p, button, render } from "./helpers/ui";

render({ count: 2020}, (state, setState) => 
	div(
		div(
			p(`Hello, Marco!`),
			p(`Year: ${state.count}`)
		),
		div(
			button("plus", () => {
				setState({
					count: state.count + 1,
				});
			})
		)
	)
);
```

2022-04-10 15:16 UTC, wonsss commented on src/ts/components/Login.ts
> +loginTemplate.innerHTML = `
웹컴포넌트에서 shadow Dom 내에 있는 CSS의 scope는 해당 커스텀 엘리먼트에 제한되어 캡슐화되는 것으로 알고 있습니다. 이렇게 CSS, HTML, JS가 모여 있으면  나중에  해당 웹컴포넌트들을 재사용할 때 조금 더 유용하지 않을까 싶습니다.
그리고 웹컴포넌트 shadowDom 내부로 외부 CSS 파일을 import하여 사용하는 방법을 찾아본 결과, 인라인 스타일 내부에 `@import 해당스타일파일.css` 코드를 추가하면 됨을 알게 되었습니다.  
> 참고
[CSS-tricks : Stryling-a-web-compoent](https://css-tricks.com/styling-a-web-component/)

2022-04-10 15:31 UTC, wonsss commented on src/ts/components/Login.ts
> +  closeModalDimmer = (event) => {
말씀해주신 것처럼, 매번 셀렉팅하는 것보다 멤버 변수로 저장하여 사용하는 방법이 훨씬 낫겠네요.
그리고 앞으로 삼항연산자 사용 시, 함수 호출을 하게 되면 혹시 가독성을 해치지 않는지 고민하면서 사용해보겠습니다. 😄 
[♻️ closeModalDimmer 리팩토링](https://github.com/woowacourse/javascript-vendingmachine/pull/68/commits/97aa3ade812d533bbac89ae599c943274ec933a0)

2022-04-10 15:33 UTC, wonsss commented on src/ts/views/PurchaseView.ts
> +  private renderRefundTable = () => {};
ㅠㅠ불필요한 코드가 남아있었네요. PR 제출 전에 꼼꼼하게 보도록 노력하겠습니다.
[🚚 불필요한 코드 삭제](https://github.com/woowacourse/javascript-vendingmachine/pull/68/commits/c5ff2c40cf607e79bc7d2a1118682b14db9f4d9f)

2022-04-10 15:37 UTC, wonsss commented on cypress/integration/purchase.spec.js
> +  it('사용자는 규칙에 적합한 금액을 투입할 수 있다', () => {
사용자가 투입할 수 있는 금액의 기준은 "매번 투입 금액이 10원으로 나누어 떨어져야 하고, 최대 누적 투입 금액은 10,000원 이하여야 한다"는 것입니다.
테스트코드에 해당 설명이 부족했네요. 설명을 추가해보았는데, 괜찮을까요?
```js
  it('사용자는 규칙(10의 배수, 누적 10,000원 이하)에 적합한 금액을 투입할 수 있다', () => {
```

2022-04-10 15:46 UTC, wonsss commented on cypress/integration/purchase.spec.js
> +      _name: '사이다',
언더바는 private 프로퍼티를 구분하기 위해 사용하였습니다.
`Product.ts`에서는 Product 클래스의 private 멤버변수로 `_name`, `_price`, `_quantity`를 지정했기 때문에, 해당 테스트코드에서 직접적으로 localStorage에 setItem을 할 때, 같은 프로퍼티명이 사용된 객체를 넣어주었습니다.
아직 타입스크립트에서 private 사용 방법이 헷갈리네요. 이렇게 언더바를 사용하는 방법이 혹시 어색할까요?

2022-04-10 16:04 UTC, wonsss commented on cypress/integration/purchase.spec.js
> +    cy.get('#purchase-tab-coin-10').last().should('have.text', '4');
이런 방법이 있었군요! alias를 사용하여 리팩토링해보았습니다.

[♻️ alias를 활용하여 테스트코드 중복 제거](https://github.com/woowacourse/javascript-vendingmachine/pull/68/commits/a211d3fda33731342c1fe7eaa1a82a3098c39b86)

2022-04-10 16:14 UTC, wonsss commented on src/ts/components/renderer.ts
> +};
render하는 함수들을 한 파일에 모으려고 시도하려고 했는데 잘 되지 않았네요. renderer 파일의 함수들을 다시 살펴본 결과, renderPrivatePage와 renderPublicPage는 router에서만 사용되므로 말씀대로 router에 위치하도록 수정하는 것이 적절할 것 같아요. 그리고 renderComponent 함수는 utils 파일로 옮긴 후, render파일을 삭제해보았습니다. 😄 
[♻️ renderer 파일의 함수 위치 재조정](https://github.com/woowacourse/javascript-vendingmachine/pull/68/commits/0a9067e06763d093c7c5e9f8c6e8d023293da606)

2022-04-10 19:39 UTC, wonsss commented
> "마르코님 생각하신것처럼 미리 hide로 가리는건 문제가 있죠. 필요한 부분만 insertAdjacent하여 렌더링하는것이 좋을것 같습니다."

로그인 여부에 따라 접근 가능한 페이지만 렌더링할 수 있도록 수정하였습니다.
[✨ 로그인 여부에 따라 접근 가능한 페이지만 렌더링](https://github.com/woowacourse/javascript-vendingmachine/pull/68/commits/0b572bcba12e985a767a44460f6563b0df5f866e)

2022-04-10 23:08 UTC, wonsss commented
> "로그인과 회원가입은 url로 접근하는게 좋을것 같습니다. "

로그인과 회원가입 페이지가 url로 접근될 수 있도록 수정하였습니다.
  - 로그인 url : https://wonsss.github.io/javascript-vendingmachine/#!/login
  - 회원가입 url : https://wonsss.github.io/javascript-vendingmachine/#!/signup

2022-04-10 23:20 UTC, wonsss commented
로컬에서 설치 및 실행방법을 리드미 문서에 추가하였습니다.

```plain
## 로컬에서 설치 및 실행 방법

1. 필수 npm package를 설치한다 : `npm install`
2. `.env` 파일을 `.env.example` 파일을 참고하여 만든다.
3. 프로젝트를 시작한다 : `npm run start`
4. UNIT 테스트를 시작한다 : `npm run test`
5. E2E 테스트를 시작한다 : `npm run cypress:open`
```

2022-04-11 06:34 UTC, hyoungnam commented on cypress/integration/purchase.spec.js
> +  it('사용자는 규칙에 적합한 금액을 투입할 수 있다', () => {
네 성공케이스가 어떤 조건인지 명시적이네요:)

2022-04-11 06:37 UTC, hyoungnam commented on cypress/integration/purchase.spec.js
> +      _name: '사이다',
아마 자바스크립트 클래스에서 private 문법이 지원되지 않았을때 사용하던 컨벤션으로 알고있습니다. 멤버변수일때는 말씀하신 용도로 사용하는것 같아 코멘트를 남기지 않았는데 테스트코드에서 보여서 질문했습니다. 지금 class가 아닌 객체로 하고있으니 붙여주지 않아도 될것 같기도 하고요. 마르코님이 결정하시면 될것 같네요!

2022-04-11 06:48 UTC, hyoungnam requested changes
마르코님~! 간단하게 수정이 필요한곳이 보여서 추가 코멘트 남겼습니다 확인해주세요

2022-04-11 06:48 UTC, hyoungnam commented on src/ts/views/View.ts
> +    $('sign-up') ? $('sign-up').remove() : false;
true면 함수를 호출하고 false이면 false를 반환하지만 반환값을 사용하는 코드는 없는듯 합니다. 
&& 연산자를 활용해서 로직을 충분히 짤수있을것 같아요

2022-04-11 06:48 UTC, hyoungnam commented on src/ts/views/View.ts
> +        new PurchaseView(this.vendingMachine).render();
페이지 렌더링할때마다 새로 인스턴스를 만드는거 같은데 각 페이지뷰들을 멤버변수로 만들고 메소드를 render 메소드를 호출하는게 좋지 않을까요?

2022-04-11 06:48 UTC, hyoungnam commented on src/ts/views/View.ts
> +      : this.$userMenu.shadowRoot.querySelector('#menu').classList.add('hide');
밑에 코멘트와 같습니다

2022-04-11 07:02 UTC, wonsss commented on src/ts/views/View.ts
> +    $('sign-up') ? $('sign-up').remove() : false;
아하!! 넵 && 연산자를 활용하니까 더 낫네요. 피드백 덕분에 앞으로 이 부분도 잊지 않고 잘 쓸 수 있을 것 같아요! 감사합니다.

[♻️ 삼항조건연산자를 && 연산자를 활용하여 리팩토링](https://github.com/woowacourse/javascript-vendingmachine/pull/68/commits/566f54bdb0aabf37ff39df54dc8ae93d5addfaae)

2022-04-11 07:02 UTC, wonsss commented on src/ts/views/View.ts
> +      : this.$userMenu.shadowRoot.querySelector('#menu').classList.add('hide');
넵! 수정하였습니다!

[♻️ 삼항조건연산자를 && 연산자를 활용하여 리팩토링](https://github.com/woowacourse/javascript-vendingmachine/pull/68/commits/566f54bdb0aabf37ff39df54dc8ae93d5addfaae)

2022-04-11 07:19 UTC, wonsss commented on src/ts/views/View.ts
> +        new PurchaseView(this.vendingMachine).render();
말씀처럼 매번 새 인스턴스를 만들 필요가 없었네요. 각 페이지뷰를 멤버변수로 만들어 render 메소드로 호출하도록 리팩토링하였습니다. 😄 
[♻️ 각 view의 render 메서드 호출 시 인스터스 새로 생성하지 않고 멤버변수 호출하여 사용하기](https://github.com/woowacourse/javascript-vendingmachine/pull/68/commits/86debbe08d645c8719d5abb75341a14bc9e84cf4)

2022-04-11 07:49 UTC, wonsss commented on cypress/integration/purchase.spec.js
> +      _name: '사이다',
여러 타입스크립트 컨벤션에서 private에 대한 언더스코어를 지양하는 것으로 알고 있긴 했는데, 언더스코어와 같은 prefix없이 동일한 식별자명으로 private 프로퍼티 외에 setter나 getter를 사용하려고 하니, 타입스크립트가 중복 에러를 발생시키더라구요. 그래서 인터넷에서 검색한 결과, 스택오버플로우에서도 이런 경우에는  언더스코어를  사용하는 것이 낫다는 답변을 확인하게 되어 언더스코어를 사용해보았습니다.

[스택오버플로우 - naming-convention-for-class-properties-in-typescript ](https://stackoverflow.com/questions/40587873/naming-convention-for-class-properties-in-typescript)

해당 테스트코드에서는  `상품 구매` 테스트에 집중하려고 하였고, 테스트 이전에 물품이 등록되어 있다는 상황을 가정하기 위해, 로컬스토리지에 상품 목록 객체를 넣었습니다. 넣어야 하는 상품 목록 객체는 Product.ts에서 private 프로퍼티명(언더스코어 prefix 적용된)들과 동일해야 오류가 나지 않아서, 테스트코드에서도 해당 객체의 프로퍼티명들의 앞에 언더스코어를 붙여주었습니다. 😄

2022-04-12 06:07 UTC, hyoungnam approved these changes
마르코님 2단계 자판기 미션 수고하셨습니다. 봄날씨 만끽하면서 재충전의 시간 잘 보내세요~!! 머지하도록 할께요:)

2022-04-12 06:07 UTC, merged